phylum-dev/cli

.github/workflows/release.yml, lib/CHANGELOG, lib/Dockerfile, lib/src/api.rs, lib/src/bin/.conf/cli.yaml, lib/src/bin/phylum-cli.bash, lib/src/bin/phylum-cli.rs, lib/src/config.rs, lib/src/types.rs
This PR primarily adds:
* Changes to support revised (and more concise) job status response
* Add a `-V`/`--verbose` for returning more detailed job status information
In addition, the following modifications are included:
* Check the environment for a api token first (`PHYLUM_API_KEY`), and prefer that to one provided in the configuration file
* Send json object output to `stdout`, all other messages to `stderr`
* Build a static musl binary for the release
=> Decreased verbosity of job status response

.github/workflows/release.yml, lib/install.sh, lib/src/bin/settings.yaml
This PR fixes both the release.yml and install.sh to handle GH releases and building phylum-cli from source from a common code path. 
Previously, there were some hiccups if one installed the GH release package vs building from source. This also gives a consistent way to pull phylum-cli with automation by using:
`curl --silent "https://api.github.com/repos/phylum-dev/cli/releases/latest" | jq -r '.assets[] | select(.name | contains("phylum-cli-release.zip")) | .browser_download_url' | xargs curl -sLO`
=> Fix release.yml and install.sh for GH releases

lib/install.sh
This PR does 2 things:
1. ensure that settings won't be overwritten if a file already exists at `~/.phylum/settings.yaml`.
2. update the path to copy the phylum-cli binary when building from source
=> Fix settings overwrite and binary install paths

CHANGELOG, bindings/python/Cargo.lock, bindings/python/Cargo.toml, bindings/python/src/lib.rs, bump_version.sh, lib/Cargo.lock, lib/Cargo.toml, lib/src/api.rs, lib/src/bin/.conf/cli.yaml, lib/src/bin/phylum-cli.bash, lib/src/bin/phylum-cli.rs, lib/src/types.rs, lib/tests/cmd.rs
This PR addresses #13 , specifically adding support for immediately returning status on package submission, and updates to indicate the completion status of jobs along with their constituent packages.
In addition, a timeout setting for api requests has been provided.
=> Adding support for immediate status after package submission

lib/Cargo.lock, lib/Cargo.toml, lib/src/api.rs, lib/src/bin/.conf/cli.yaml, lib/src/bin/phylum-cli.rs, lib/src/bin/phylum.bash, lib/src/config.rs, lib/src/render.rs, lib/src/types.rs
Update the authentication mechanism to conform to requested changes in https://github.com/phylum-dev/cli/issues/20.
Adds the `auth` subcommand which has it's own subcommands:
* `ph auth keys` - Manage user keys
* `ph auth register` - Interactively register a new user 
* `ph auth login` - Interactively login a user
=> Add new subcommand for `auth`

lib/install.sh
Trivial change
I happened upon this while Derrik was helping me get localdev going.
The trailing `/` in the addition to `$PATH` resulted in a path with an empty segment:
```shell
$ which phylum
<home dir>/.phylum//phylum
```
so I removed the trailing `/`.
=> Remove trailing `/` from `~/.phylum` path addition

lib/Cargo.lock, lib/Cargo.toml, lib/src/summarize.rs, lib/src/types.rs
Prints a formatted table showing the package vulnerabilities when running either of:
* `phylum package <pkg_name> <pkg_version>`
* `phylum history <job_id> --verbose`
=> Show vulnerabilities when checking package status

lib/src/api.rs, lib/src/summarize.rs, lib/src/types.rs
Display the project name (rather than the project id) in the summary output.
=> Include the project name in the display

lib/src/render.rs, lib/src/summarize.rs
Likely fix for #45.  Holding off on linking that issue to close till we've performed additional testing / verification.
=> Include packages with perfect (1.0) scores in the histogram count

lib/src/api.rs, lib/src/bin/.conf/cli.yaml, lib/src/bin/phylum-cli.rs
- Print user message when no project info available
- Default to showing keys when `phylum auth keys` run w/o args
- Make arg to `phylum auth keys remove` required
=> Clean up / minor fixes

lib/build.sh, lib/install.sh
* Use dirname to get location of script, then invoke build
relative to that
=> Make build scripts more location robust

lib/src/lockfiles/parsers.rs
Some `Gemfile.lock` files have `GIT` or other entries before the `GEM` header.  Relaxed parsing to allow for that.
=> Allow additional entries before the `GEM` header

lib/src/api.rs, lib/src/bin/.conf/cli.yaml, lib/src/bin/phylum-cli.rs, lib/src/config.rs, lib/src/render.rs, lib/src/summarize.rs, lib/src/types.rs
* Take appropriate action when a threshold is not met (warn, break the build, or do nothing)
* Use the templated issues set up for heuristics when displaying verbose output (formatted and json)
* Clean up text formatting for issues and vulnerabilities
* Add the ability to run `phylum history current` to see results for the most recent job in the current project
=> Updates to support threshold actions and issues templates

lib/src/bin/phylum-cli.rs
We previously only supported Linux builds. We now have a PR out for
building the macOS distribution as well. This means that we need to also
support updates for macOS.
This adds a compile time check for the various operating systems we
support to ensure we are pulling the correct binary.
This depends on #74 and closes #75.
=> Support updating for macOS builds.

lib/src/bin/phylum-cli.rs, lib/src/update.rs
There was an issue moving update files after they had been downloaded
and the signatures had been verified on tmpfs. Update files would be
downloaded and temporarily stored in `/tmp` which existed on tmpfs. Any
attempts to *move* the files to the disk (a separate file system) would
trigger a panic due to crossing boundaries.
This update changes to a *copy* and remove operation from the temporary file
location.
Also added an additional signature verification that occurs after the
files have been moved to the final install location. This is to address
a possible race condition where an attacker may change the file in
`tmp/` after the signature verification has occurred, but before we have
copied the file to the final location.
closes #90
=> Fix update issue for tmpfs

lib/src/update.rs
Previously, when an update occurred we were moving the binary to the
final install location after verifying the signatures. We changed this
to a move in a recent change to ensure that we could avoid crossing
filesystem boundaries in the event a user was using tmpfs or similar.
The name in the copy ended up being the binary asset name, which took on
the form of `phylum-<os>-<arch>`. However. the installer (and the user)
expects this to be `phylum`. This change simply ensures that we use the
`phylum` name for binaries after update/install.
=> Use proper name during update

lib/src/bin/.conf/cli.yaml, lib/src/bin/_phylum, lib/src/bin/phylum.bash, lib/src/bin/phylum.fish, lib/src/types.rs
We recently changed how the descriptions were being handled. This caused a deserialization failure when verbosity was specified.
Additionally, removed the confusing `-V` flag for verbosity that conflicted with the default clap `-V` flag for version. Made the lowercase v (i.e. `-v`) the shorthand for verbosity to avoid confusion.
=> Fix deserialization bug and confusing shorthands

lib/src/bin/.conf/cli.yaml, lib/src/bin/_phylum, lib/src/bin/phylum-cli/commands/auth.rs, lib/src/bin/phylum-cli/commands/jobs.rs, lib/src/bin/phylum-cli/commands/packages.rs, lib/src/bin/phylum-cli/commands/projects.rs, lib/src/bin/phylum-cli/main.rs, lib/src/bin/phylum-cli/print.rs, lib/src/bin/phylum.bash, lib/src/bin/phylum.fish, lib/src/filter.rs, lib/src/lib.rs, lib/src/summarize.rs, lib/src/types.rs
Adds support for basic filtering of the issues displayed based on the severity and the risk domain of each issue.  For example, providing the option
`--filter=high,auth,engineering`
to either the `phylum analyze` or `phylum history` subcommands will filter the displayed issues to include only those at risk level "high" or higher and that are included in the "Author" or "Engineering" risk domains.
=> Add support for filtering issues based on severity / domain

lib/Cargo.lock, lib/Cargo.toml
https://rustsec.org/advisories/RUSTSEC-2021-0100.html
Says 0.9.8 isn't affected but 0.9.8 has been yanked, so bumped up the version.
=> Update sha2 crate due to RUSTSEC-2021-0100

.github/workflows/release.yml, lib/.cargo/config, lib/Dockerfile.macos
Add cross-compile for `aarch64` to the `macos` build to support m1 mac
=> Adding m1/arm build

.github/workflows/release.yml, .github/workflows/test.yml
The `cli` repo is not currently able to build release artifacts locally. This makes it hard to test changes and iterate locally. Further, the ability to manually run GitHub workflows was not enabled for this repository. This PR changes that, making it possible to manually run all the workflows for this repository, for any branch. There was also some light formatting changes...to fix most of what `yamllint` found (line length is the main exception).
* Partial...can't be confirmed until the changes here make it into the `development` branch
closes #183
=> Allow for manually running GitHub workflows

.github/workflows/test.yml, cli/src/bin/phylum.rs, cli/src/lib.rs, cli/src/update/mod.rs, cli/src/update/unix.rs, cli/src/update/unsupported.rs
Use a matrix in the `test.yml` workflow to ensure that the CLI builds and all tests pass Linux, macos, and Windows. This also adds a scheduled run of the workflow to ensure that we are notified if the build begins to fail for external reasons (e.g., a new rust release). And this splits the self-update functions by platform in order to fix the build on Windows and close #200
=> Add Windows builds to test workflow

Cargo.lock, cli/Cargo.toml, cli/src/bin/phylum.rs, cli/src/update/unix.rs, docs/updating.md
Implement `phylum update` by downloading the appropriate zip file and running `install.sh`
=> Use zip archives for `phylum update`

cli/src/install.sh
This migrates the phylum CLI install script to posix /bin/sh, which will
allow for execution on more platforms.
Closes #216.
=> Migrate install script to POSIX sh

.github/workflows/test.yml, Cargo.lock, cli/Cargo.toml
Tracking the `master` branch of `phylum-types` creates an over-complicated workflow. We are already using `Cargo.lock` to lock the dependency to a specific revision until `cargo update` is run.
It is much more useful for us to develop against the `development` branch so that we can quickly find and fix any problems that might arise. This PR makes that switch.
=> Follow development branch of phylum-types

Cargo.lock, cli/src/commands/lock_files.rs, cli/src/lockfiles/java.rs, cli/src/lockfiles/mod.rs, cli/src/lockfiles/python.rs, cli/tests/fixtures/poetry.lock, docs/analyzing-dependencies.md
This adds support for analyzing the Python `poetry.lock` package lock
format.
Since this format includes a metadata field with a version indicator, a
warning is emitted when a breaking change that isn't supported by
`phylum` was detected.
While it would be possible to abort completely, it's not unlikely that a
format change does not touch the information required by `phylum` at
all. So we attempt to continue anyway and just let the user know that
some packages might not have been analyzed.
Closes #237.
---
=> Add Python poetry.lock support

.github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/test.yml
Publish the docs when a new release is tagged rather than when a merge to `master` occurs. This is required now that we no longer have a `master` branch.
=> ci: Run doc workflow on tag instead of master

cli/src/summarize.rs
Since a package uploaded to NPM might not necessarily be JavaScript, the
existing `phylum analyze` description could be misleading.
To improve on this, the `Language` and `Type` fields have been
consolidated into an `Ecosystem` field which just prints the package
repository rather than a guess at the language used in the package.
Closes #129.
=> Replace Language/Type with Ecosystem

.github/workflows/release.yml, Cargo.lock, cli/Cargo.toml, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/update/unix.rs, cli/src/update/unsupported.rs
Use [`git_version`](https://docs.rs/git-version/latest/git_version/) to provide the version number for the CLI.
If the CLI is built from a tagged commit, it will display the tag. Otherwise, it displays the most recent tag, followed by the number of commits difference and the hash of the current commit. If changes have been made to the working directory, a `-modified` suffix is added. Here is an example from this branch:
```
❯ ./target/debug/phylum version
✅ phylum (Version v2.0.0-4-gd43325e)
```
Fixes #124
=> Use git_version for version numbers

release.sh
This PR aims to improve `release.sh` so that our releases use signed tags and more descriptive commit messages.
It also gives the user more information to work with by listing a log of commits since the latest release.
=> Sign release tags and be descriptive

cli/src/render.rs
This replaces the Type/Language fields in the `phylum package` command
with a new `Ecosystem` field, similar to what has been done in 4227456.
Closes #254.
=> Use Ecosystem in `phylum package` output

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/package-lock-v6.json, cli/tests/fixtures/package-lock.json
This adds initial support for the new package-lock.json format
introduced in version 7, where a new `packages` section was introduced
with the goal of replacing `dependencies`.
One major change with the new `dependencies` section is that a full path
to each dependency is specified, rather than just the dependencies name
(e.g. "node_modules/accepts" vs. "accepts"). To accomodate for this,
everything before the last `node_modules/` in the package identifier is
truncated, returning only the trailing part of the path.
While extracting the module name out of the path has worked in all
examples I've tested, the ideal solution would likely be to rely on the
`resolved` field to acquire the dependencies directly rather than
relying on name resolution.
Closes #153.
=> Add support for new npm package-lock format

cli/src/render.rs
Instead of printing the "Last updated" field in `phylum package` as a
millisecond unix timestamp, it is now printed in ISO 8601, making it
human-readable.
Closes #256.
=> Format "Last updated" field with ISO 8601

cli/src/commands/auth.rs
To ensure the `phylum auth token` command's output isn't confusing, the
checkmark in front of the token has been removed.
The token is now also written to `stdout` instead of `stderr`, which
should allow for much better interaction between `auth token` and shell
pipes.
Closes #252.
=> Remove checkmark from `auth token` command

cli/src/bin/phylum.rs, cli/src/commands/auth.rs, cli/src/commands/jobs.rs, cli/src/commands/mod.rs, cli/src/commands/packages.rs, cli/src/commands/projects.rs
Several paths of the Phylum CLI would print warnings/errors to the user,
but still set and exit code of `0`. This makes it difficult for for
automated tools to verify success and can confuse users.
As a solution, the `CommandValue` enum has been changed, replacing the
`CommandValue::Void` variant with `CommandValue::Code`. This code is
then used on exit instead of the fixed `0` which was used for
`CommandValue::Void`.
This also introduces a few simplifications to the error/CommandValue
handling, removing unnecessary code and inlining unnecessary
abstractions. This hopefully improves transparency of the process and
makes the usage consistent.
Some functions relying on `CommandValue::Void` as a replacement to `()`
without ever propagating it have been switched to `anyhow::Result<()>`. …
=> Set appropriate exit codes on failure

Cargo.lock, cli/Cargo.toml, cli/src/print.rs, cli/src/render.rs, cli/src/summarize.rs
Since a lot of output in the Phylum CLI relies on tables, it's important
that text does not exceed the maximum cell length. The most likely
culprit for this is the `project`, which can be freely defined by the
user.
All instances of the project name output are now truncated to the
respective cell length and a truncation is indicated using the ellipsis
symbol.
To ensure this works for project names in any language, the length of
the cells is calculated using the `unicode-width` crate.
Closes #127.
=> Truncate excessive project names

cli/src/commands/projects.rs
This removes the pretty-print table header from the output of the
`phylum projects --json` command.
Closes #263.
=> Remove table header from projects list json

cli/src/lockfiles/parsers/mod.rs, cli/src/lockfiles/parsers/pypi.rs, cli/src/lockfiles/python.rs, cli/tests/fixtures/requirements.txt
This PR adjusts our parsing for `requirements.txt` files so that we ignore package extras (i.e., stuff in square brackets after the package name).
I've also added a new `ws` utility to the `parsers` module that makes eating whitepspace a bit easier. This utility was taken basically verbatim from `nom::recipes`, but I use `space0` instead of `multispace0` so that it doesn't eat newlines.
Fixes #267
=> fix: Parse package extras in Python requirements.txt files

cli/src/app.rs, cli/src/commands/jobs.rs
This patch allows running `phylum analyze` without a `.phylum_project`
file present by adding the new `-p`/`--project` arguments for specifying
a project name for analysis.
While the UUID is required to request a project analysis, the project
name was chosen as parameter for eas-of-use and the UUID is retrieved
from the API.
Closes #144.
=> Add --project parameter to `phylum analyze`

cli/src/lockfiles/python.rs, cli/tests/fixtures/poetry.lock
This patch filters the poetry lockfile to ensure only packages which are
present in PyPi are submitted, to avoid potential dependency confusion.
To ensure the poetry lockfile parser's robustness, a new test lockfile
has been created which makes use of every possible dependency type other
than `legacy`.
Closes #269.
=> Filter non-PyPi dependencies from poetry lockfile

cli/src/config.rs, cli/src/install.sh
Previously phylum's installer would put all files into `~/.phylum` and
retrieve the configuration file from there. This leads to a rather
cluttered home directory which is why the XDG directories spec is
usually preferred.
The CLI will now check the XDG config directory first
(`${XDG_CONFIG_HOME:-${HOME}/.config}/phylum/settings.yaml`), then fall
back to the old config path if that isn't present.
The installer will put the completions in the XDG data directory
(`${XDG_DATA_HOME:-${HOME}/.local/share}/phylum`) and the binary in
`${HOME}/.local/bin/`.
Since the `${HOME}/.local/bin` path is sometimes included in the path
already, without being present in the shell config itself, we check the
current `$PATH` first to try and detect if we need to add it or not.
Closes #224.
=> Follow XDG directories spec

.github/workflows/release.yml, .github/workflows/test.yml
This PR contains the few code changes that need to happen in order to change the default branch to `main`
Nothing depends on us, so it's pretty simple. If/when this is merged, I'll swap the default branch, update all other PRs to target `main`, and delete the `development` branch.
=> Rename default branch to main

cli/src/install.sh
To ensure that the line added to the shell rc files is interpreted
properly, a newline has been added to the start of the line in addition
to the one at the end.
Closes #284.
=> Add newline to shell rc files

cli/src/config.rs, cli/src/install.sh
Following the XDG spec, new directories will now be created with the
mode 700 set instead of 755.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> If, when attempting to write a file, the destination directory is
> non-existent an attempt should be made to create it with permission
> 0700. If the destination directory exists already the permissions
> should not be changed. The application should be prepared to handle
> the case where the file could not be written, either because the
> directory was non-existent and could not be created, or for any other
> reason. In such case it may choose to present an error message to the
> user.
Closes #285.
=> Create directory with mode 700 by default

cli/src/render.rs
The phylum history project scores were formatted to 5 digits after
applying the ANSI colors. However ANSI colors alone already exceeded the
target size.
To ensure the number of digits in the project score doesn't affect
formatting, all padding is now done **before** the ANSI colors are
applied.
Closes #296.
=> Fix formatting of `phylum history` project scores

cli/src/app.rs
Add `value_hint` calls to filename arguments so that `clap_complete` generates better tab completion files and `zsh` allows tab completion of file arguments.
Fixes #299
=> Use value hints to improve tab completion

cli/src/app.rs, cli/src/commands/jobs.rs, cli/src/render.rs, cli/src/summarize.rs
This removes the `phylum history project` subcommand from the
documentation and prints a warninng when running it without the `--json`
flag.
Users are instructed to instead use the `phylum project` command.
Closes #277.
=> Add `--project` option to `phylum history`

cli/Cargo.toml, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/mod.rs, cli/src/commands/uninstall.rs, cli/src/config.rs
In #236 a shell script was proposed to allow for uninstallation of the
Phylum CLI, however the usage of that command turned out to be a bit
awkward.
This patch instead introduces the new `phylum uninstall` CLI option
which will automatically remove the CLI without having to go through the
hassle of acquiring a separate uninstallation script.
To ensure uninstallation never removes something it shouldn't, the shell
configs are only edited when the full text added by the installer can be
found. To ensure this works as often as possible, the `install.sh`
script had to be modified to always include the completion
initialization, since this is commonly present already.
Closes #206.
=> Add uninstall subcommand to phylum

.github/dependabot.yml
Use dependabot to update our Rust and Github Action dependencies.
Fixes #223
=> Use Dependabot for dependency updates

Cargo.lock, cli/Cargo.toml, cli/src/api/mod.rs, cli/src/commands/uninstall.rs
This should take some of the workload off of poor ol' Dependabot.
With the exception of `nom`, all of these updates are SemVer compatible updates. Dependabot still has the job of alerting us of breaking changes.
=> Bump dependencies

cli/src/install.sh
Using `mkdir -m` has two issues. First, it always sets the mode rather
than only setting it when it creates the directory. Second, when
combined with `-p`, it only sets that mode for the last directory in the
chain. This method of using umask fixes both problems.
=> Set permissions with umask instead of mkdir -m

Cargo.lock, cli/Cargo.toml, cli/src/bin/phylum.rs, cli/src/prompt.rs, xtask/Cargo.toml, xtask/src/main.rs
This PR bumps dependencies including many dependencies where the update includes a breaking change. I read through the Changelogs for these dependencies and updated our code accordingly
=> Bump dependencies with breaking changes

cli/src/app.rs, cli/src/commands/auth.rs
This patch adds the new `--bearer` parameter which will print the
short-lived API access token rather than the long-lived refresh token.
Using this new command it should be much easier to make `curl` requests
to the phylum API, without having to handle login manually.
Closes #319.
=> Add `--bearer` parameter to `phylum auth token`

release.sh
While releasing the last handful of CLI versions it became clear that
the release script used to do so could use a refresh. For one, it
automated _everything_, which felt risky and most of the time the script
would be aborted before it could tag and push the changes. Another
minor annoyance was not remembering the format of the version or
changelog entry. Additionally, the git log summary would only show from
the last tag, not taking into account that the last tag could be from a
pre-release.
These issues have been addressed, along with some minor
refactoring and formatting. It is still just a basic shell script and
there could certainly be better ways yet.
=> chore: refresh the release script

.github/PULL_REQUEST_TEMPLATE.md
This patch removes the boilerplate from our pull request template. What
is left is only the checklist, which is important to ensure that nothing
is missed before a PR is merged.
If developers are using detailed commit messages (like this one), PRs
will automatically be created with the detailed commit message followed
by the checklist, which is exactly how we want them.
Fix #321.
=> Simplify the PR template

Cargo.lock, cli/src/commands/project.rs
This is the quickest way to fix #331. Even in staging, the API is not
currently accepting the `group_name` parameter for project creation and
this is causing an error (which is getting misrepresented as being about
the characters in the project name).
=> fix: Resolve project create errors

.github/dependabot.yml, .github/workflows/cargo-update.yml
This runs a basic `cargo update` in a Github Action and creates a PR
with any changes. Combined with limiting Dependabot to major version
updates, this should resolve concerns about too many PRs and being too
strict in our Cargo.toml files.
Ref: Discussion on #325
=> Automatically run `cargo update` in a workflow

cli/src/commands/project.rs, cli/src/prompt.rs
Previously, when setting the project thresholds from the CLI, a value of
`0` would automatically disable the specified threshold. This does not
correctly represent the backend configuration, since some thresholds
cannot be disabled and it is possible to have a threshold enabled with a
value of `0`.
To address both of these issues, an explicit `Disabled` option has been
added to the interactive `set-thresholds` command, which allows
controlling the `active` state of the threshold independently from its
value.
To ensure that the "Total Project" threshold is not disabled, a special
case has been added which will inform the user that a value must be set
for this threshold.
Closes #288.
=> Add explicit option to disable thresholds from CLI

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/yarn.lock
Yarn allows patching dependencies, which produces a local patch file
applied on top of a dependency. Before this patch, this would cause an
error in the lockfile parser.
To provide the most value possible, this patch adds support for parsing
these patched dependencies and extracts the original package, while
discarding the local patch information. This allows analyzing the
unpatched dependency for vulnerabilities.
Closes #342.
=> Fix yarn lockfile parsing with patched deps

cli/src/lockfiles/java.rs, cli/src/lockfiles/javascript.rs, cli/src/lockfiles/mod.rs, cli/src/lockfiles/python.rs, cli/src/lockfiles/ruby.rs
We make heavy use of the anyhow crate everywhere else and it makes sense
to use it in the parsers as well.
This is just the first of a series of refactors to the parsers that I
hope to make in order to improve their ergonomics and assist in
implementing a `parse` subcommand (Ref: #346)
=> Use anyhow instead of boxed errors for parsers

cli/src/commands/jobs.rs, cli/src/commands/lock_files.rs
The existing error for missing lockfiles was somewhat opaque, making it
difficult for users to figure out how to resolve this issue.
Before:
```
[2022-05-04T21:04:44Z WARN  phylum_cli::commands::lock_files] Attempting to obtain packages from unrecognized lockfile type: reqiurements.txt
[2022-05-04T21:04:44Z ERROR phylum] Execution failed: Unable to locate any valid package in package lockfile
❗ Error: Execution failed caused by: Unable to locate any valid package in package lockfile
```
After:
```
[2022-05-05T19:44:04Z ERROR phylum] Execution failed: Lockfile "/tmp/xxx" does not exist
❗ Error: Execution failed caused by: Lockfile "/tmp/xxx" does not exist
```
Closes #347.
=> Add better error for missing lockfiles

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/yarn.lock
The yarn lockfile allows various different resolvers other than the
standard one which pulls from npm. Some of these include the filesystem
(@workspace), http/s (@http/s), and ssh (@ssh).
To ensure our parser is robust against all types of possible resolvers,
this patch checks for the presence of `@npm` to ensure that the
dependency can be resolved through npm. All other dependencies are
silently ignored.
This comes with the trade-off that it is easier for a failure to parse a
dependency, that can be resolved through npm, to be hidden from the
user, opening up the possibility for hidden vulnerabilities. It also
assumes that no package scope starts with `@npm`, otherwise the parser
might throw an error.
Closes #344.
=> Fix yarn lockfile with unknown resolvers

cli/src/commands/lock_files.rs, cli/src/lockfiles/csharp.rs, cli/src/lockfiles/java.rs, cli/src/lockfiles/javascript.rs, cli/src/lockfiles/mod.rs, cli/src/lockfiles/python.rs, cli/src/lockfiles/ruby.rs
This patch attempts to reduce the maintenance overhead of changing the
`lock_files.rs` by providing macros and helper functions to generate the
necessary output rather than relying on repeating the same code over and
over.
=> Remove redundancy from lock_files.rs

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/render.rs, cli/src/types.rs
The `/api/v0/health` endpoint has existed for a while, but we have
continued to use the old endpoint. This patch closes #370
=>  Use new endpoint for ping 

Cargo.lock, cli/Cargo.toml, cli/src/api/mod.rs, cli/src/commands/jobs.rs, cli/src/commands/project.rs
It turns out that we don't actually need this as a direct dependency
because `phylum_types` has type aliases for all of this.
Doing it this way has pros and cons. Maybe someday we'll decide that the
aliases in `phylum_types` don't actually make sense or that they should
actually use the newtype pattern. But for now, they exist, so we might
as well use them.
As an nice bonus, this means we won't have to worry about coordinating
our version bump of the uuid crate with phylum-dev/phylum-types#27. Once
that is merged, we will automatically be upgraded (after the next cargo
update)
Closes #349
=> Remove uuid dependency

cli/src/api/mod.rs, cli/src/auth/oidc.rs, cli/src/commands/auth.rs, cli/src/update/unix.rs
This resolves an issue where an HTTP JSON error response would lead to
cryptic serde deserialization error instead of a helpful error message.
To provide better user feedback in these kind of scenarios, all
instances of json HTTP deserialization have now been changed to check
the response status before attempting deserialization. In case of an
error response, the body is logged instead of deserialized.
Closes #361.
=> Improve handling of HTTP JSON error responses

cli/src/api/mod.rs, cli/src/commands/jobs.rs, cli/src/commands/project.rs
Many of the uses of `get_project_details()` were only using that method to
get the Project ID. This split will simplify future updates to the
endpoints.
There are plans to deprecate and remove the endpoint used here. Splitting the functionality like this will help us decide what endpoints to switch to when that happens.
See [this comment](https://github.com/phylum-dev/api/blob/d362b0d4fc8d423e1abc0067c854f56f44f53d49/src/endpoints/projects/endpoints.rs#L186-L191) on the API endpoint.
=> Split get_project_id into its own method

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/group.rs, cli/src/commands/jobs.rs, cli/src/commands/mod.rs, cli/src/commands/project.rs, cli/src/config.rs, cli/src/print.rs, cli/src/render.rs, cli/src/summarize.rs
This adds support for user groups, which allow multiple people to have
access to the same projects.
A group can now be specified for the following commands:
- `phylum project`
- `phylum project create`
- `phylum project list`
- `phylum project link`
- `phylum project set-thresholds`
- `phylum analyze`
- `phylum batch`
Additionally two commands have been added which allow interacting with
groups:
- `phylum group list`
- `phylum group create`
Closes #276.
Closes #275.
Closes #274.
=> Add group support

cli/src/commands/group.rs
Previously instead of reading the flags from the `list` subcommand,
`phylum group list` would instead read all flags from the `group`
subcommand. Thus `phylum group --json list` worked, while `phylum group
list --json` produced pretty-printed output.
To fix this, flags from the `group` subcommand are now ignored, so
`phylum group --json list` will pretty-print, while `phylum group list
--json` will output json.
=> Fix json flag with `phylum group list`

Cargo.lock, cli/Cargo.toml
There were some dependencies in `Cargo.toml` that we weren't using (or weren't using directly). This patch removes them.
=> Remove unused deps in Cargo.toml

cli/src/api/mod.rs
This type has been flawed for a few reasons:
* Deserialization for this type only happens when an HTTP 200 status
code is returned. But the API correctly uses 4xx and 5xx HTTP status
codes for errors.
* The error format does not match the format used by the API.
* Using this type results in an obscure error message when
deserialization fails:
```
data did not match any variant of untagged enum APIResult
```
As noted by @samtay in [this comment](https://github.com/phylum-dev/cli/pull/365#discussion_r869637268), API errors do not match this format.
=> Remove APIResult type

cli/src/api/mod.rs, cli/src/auth/oidc.rs, cli/src/auth/server.rs, cli/src/commands/auth.rs
This should fix #388 by correctly setting `danger_accept_invalid_certs`
on all `request::Client` objects and not just the one used for API
requests.
=> Ignore certs everywhere when requested

cli/src/lockfiles/parsers/mod.rs
The use of streaming parsers in combination with nom::Finish will
occasionally cause a panic...
Fixes #402
=> Don't use streaming parsers

cli/src/bin/phylum.rs, cli/src/commands/mod.rs, docs/analyzing-dependencies.md
Previously a failure to meet project thresholds would result in the
generic exit code of 1, making it difficult to identify the type of
error that occurred.
Instead of returning a generic exit code of 1, a special exit code of
100 has been introduced to identify failure to meet the project
thresholds.
Closes #403.
=> Emit unique exit code when failing thresholds

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/auth/oidc.rs, cli/src/auth/server.rs, cli/src/commands/auth.rs, cli/src/config.rs, cli/src/test.rs
Previously the `oidc_discovery_url` had to be specified in the
configuration file to handle the user authentication.
This patch makes use of the new `/.well-known/openid-configuration`
endpoint of the API, which automatically redirects to the correct URL.
Closes #373.
=> Use new API endpoint for OIDC redirect

CHANGELOG, Cargo.lock, cli/Cargo.toml
Bump to v3.5.0 - Automatically detect OIDC URL
Release-Version: v3.5.0
Release-Summary: Automatically detect OIDC URL
=> Bump to v3.5.0 - Automatically detect OIDC URL

Cargo.lock, cli/Cargo.toml, cli/src/bin/phylum.rs, cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/src/deno.rs, cli/src/lib.rs
This adds a deno runtime which is capable of executing the `entry_point`
of an extension as an ES module.
This supports both traditional JavaScript modules and transpiled
TypeScript without any additional dependencies for the user.
Module imports are resolved through the filesystem relative to the entry
point, allowing for multiple source files to be shipped with a single
executable.
Closes #417.
=> Add deno runtime for executing extensions

cli/src/app.rs
This resolves an issue when trying to run the CLI on Windows, which
would cause a stack overflow due to the clap CLI parsing.
To reduce the amount of stack necessary to parse the CLI, all instances
of the `arg!` macro have been replaced with manually built `clap::Arg`
arguments.
Closes #424.
=> Fix stack overflow on Windows

cli/src/commands/parse.rs, cli/src/lockfiles/csharp.rs, cli/src/lockfiles/java.rs, cli/src/lockfiles/javascript.rs, cli/src/lockfiles/mod.rs, cli/src/lockfiles/python.rs, cli/src/lockfiles/ruby.rs
This changes our parsers to be strategy objects so that they are a bit
easier to use. This allows us to simplify the LOCKFILE_PARSERS array in
commands/parser.rs and use that array in try_get_packages instead of a
macro.
Closes #347
As @cd-work suggested in #398:
> Maybe having the parsers completely stateless, just taking a &str as parameter would be the way to go.
This patch takes that idea and runs with it.
=> Use unit structs for parsers

cli/Cargo.toml, cli/src/lib.rs, docs/building.md
Unfortunately, it looks like the deno crates we are using fail to build
on x86_64-unknown-linux-musl... That is now recorded in #426, but in the
meantime, this change avoids including deno in our default builds
While making this change, I decided to use the `dep:` syntax for features which was introduced in Rust 1.60. I have updated our MSRV and docs accordingly.
=> Only use deno with the extensions feature

.github/workflows/test.yml
This adds a new shellcheck step to CI, which will validate that all
scripts within the repository are valid `sh` scripts without major style
issues.
Since shellcheck's lint might change independently, this step is
excluded from CI jobs running on a schedule.
Closes #215.
=> Add shellcheck to CI

cli/src/commands/extensions/mod.rs
This reserves installation of extensions without slash, allowing us to
later use this syntax to install extensions from the marketplace without
risking users accidentally installing these remote extensions when
trying to install local ones.
Closes #356.
=> Require slashes for installing local extensions

CONTRIBUTING.md
This adds documentation for users interested in contributing code or
issues/features to the Phylum CLI project.
The structure is loosely based on previous experience and existing
documentation in phylum-ci:
https://github.com/phylum-dev/phylum-ci/blob/main/CONTRIBUTING.md
Closes #435.
=> Add CONTRIBUTING.md documentation

cli/src/commands/extensions/extension.rs, cli/src/commands/uninstall.rs, cli/src/config.rs, cli/src/dirs.rs, cli/src/lib.rs
This merges together the two separate `data_dir` methods and streamlines
all the other XDG-related utility functions.
Since the only error that is possible with these methods is the very
uncommon scenario where the user's home directory does not exist, error
handling of this scenario has been made less explicit and prominent.
Due to the current order of operations, the errors should still be the
same. However this would make it more likely that in the future an
uninstall is only partially attempted due to a missing home directory.
Closes #414.
=> Unify XDG directory methods

README.md
Fixes the immediate problem of incorrect links in the README, from https://github.com/phylum-dev/cli/issues/438.
=> Update links to Phylum docs in README quickstart

cli/Cargo.toml, cli/build.rs
The build script added in this PR exists as a workaround for [this issue](https://github.com/rust-lang/rust/issues/34283).
This issue is present under Windows in debug builds.
The CLI has a long `match` statement in the body of a function. LLVM makes it so that the stack space required by the `match` statement is proportional to the sum of the stack space requirements for each branch, rather than to the maximum for all of the branches (which is what happens on higher optimization levels and on different targets). As a result, Windows debug
builds have too high a stack utilization, and will result in a stack overflow when run. By expanding the available stack space at link time, we prevent this from happening. We want to make sure this variation is only applied to the affected target(s) as …
=> Added build script as workaround for Window debug builds

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/auth/oidc.rs
This PR changes all the functions in `api::endpoints` to construct the endpoint address using the url crate. The url crate takes care of escaping the path components for us.
Using the url crate here moves the time when URL parse errors occur to earlier in the process of making a request. Previously, reqwest was doing this for us and combining any URL parse errors into the reqwest error, but now it is a distinct error type. Now we can pass the already parsed Url into reqwest.
We also handle the case where the base address in the config file contains a query string or hash, silently dropping them instead of creating invalid URLs (which would be different invalid URLs than previously when we used string concatenation).
I added at least one test for every path function. I don't know if we …
=> use url crate to build URLs

cli/src/bin/phylum.rs, cli/src/update/unix.rs
The installer prints to stdout which messes up the loading animation:
```
❯ phs update
⠍⠉ Downloading update and verifying binary signatures...
phylum-cli installer
⠋⠉ Downloading update and verifying binary signatures...    OK Copied completions to /Users/samtay/.local/share/phylum/completions
OK Completions are enabled for bash.
OK Completions are enabled for zsh.
OK Successfully installed phylum.
Source your /Users/samtay/.zshrc file, add /Users/samtay/.local/bin to your $PATH variable, or
log in to a new terminal in order to make `phylum` available.
⠋⠉ Downloading update and verifying binary signatures...
✅ Successfully updated to v3.5.0!
```
```
❯ phs update
Downloading update and verifying binary signatures... Done!
phylum-cli installer
OK Copied completions to …
```
=> Fix messed up spinner output

cli/src/install.sh
This PR ensures the `SHELL` environment variable has a default value when none exists. It also cleans up the language used in the instructions printed after install.
Closes #470
=> fix: SHELL env var assumed to exist during install

cli/src/api/endpoints.rs, cli/src/api/mod.rs
This patch updates old paths (under the /job/ prefix) that were used
with request manager and uses the canonical API paths (under the /data/
prefix).
Fix #468
=> Use canonical URL paths for the API

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/commands/extensions/api.rs, cli/src/commands/extensions/extension.rs, cli/src/deno.rs, cli/tests/fixtures/extensions/sample-extension/main.ts
The deno project provides a couple of different binaries and libraries,
the main entry point being its CLI. This CLI depends on `deno_runtime`
which in turn depends on `deno_core`.
Previously we were using `deno_core`, the lowest level library for
embedding deno. However this does not come with any utility functions
and requires including all of these manually.
This patch switches to the `deno_runtime` library instead, which is one
level above `deno_core`. While it still allows us all necessary
flexibility of `deno_core`, we now automatically get access to the Deno
API (https://doc.deno.land/deno/stable).
This change does not increase the output size or compilation time.
Closes #452.
=> Migrate from `deno_core` to `deno_runtime`

.github/CODEOWNERS
We don't need to bother the @phylum-dev/user-components team to do code reviews on CLI.
=> Remove user-components from CODEOWNERS

CHANGELOG, Cargo.lock, cli/Cargo.toml
A few bug fixes and some additional gradle support will be the main features of this release. Lots of refactors and lots of work on extensions as well, but that's still behind a feature flag.
Release-Version: v3.6.0
Release-Summary: Add support for gradle.lockfile
=> Bump to v3.6.0 - Add support for gradle.lockfile

.github/workflows/release.yml
The change in this PR is to encapsulate the `curl` based trigger's data
payload in double quotes since expressions do not expand in single
quotes. This means that the inner double quotes have to be escaped
because they are still needed since the payload includes a JSON string.
Promote the `if` condition for triggers from step to job level.
This change will ensure the Trigger job does not run for pre-releases.
Previously, the conditional was one level lower, on a step within the
job. That was confusing because the UI would show that the Job ran, but
it wasn't until drilling into the results that it would be clear that
the trigger step was skipped.
Closes #488
=> fix: phylum-ci Docker image trigger

.github/workflows/test.yml, Cargo.lock, cli/Cargo.toml
This removes the last usage of the `oldtime` feature of the `chrono` crate.
=> Bump to latest phylum-types

cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/src/lockfiles/csharp.rs, cli/src/types.rs
This patch adds a new command for automatically creating extension
skeletons in the specified repository, making the initial steps for
getting started with writing your own extensions much simpler.
Closes #412.
=> Add phylum extension new command

cli/src/commands/extensions/mod.rs, cli/tests/extensions.rs
This changes the `phylum extension add` and `phylum extension remove`
subcommands to install use `install` and `uninstall`, since the latter
is more in sync with what developers should be used to.
Some notable examples sharing this naming pattern are `cargo` and `apt`.
Closes #501.
=> Rename extension add/remove to install/uninstall

extensions/npm/PhylumExt.toml, extensions/npm/main.ts, extensions/yarn/PhylumExt.toml, extensions/yarn/main.ts
This adds two extensions for the NPM ecosystem, which provide support
for analyzing dependencies of yarn and npm lockfiles before installing
the packages themselves.
Closes #511.
=> Add npm package check extensions

cli/src/commands/extensions/mod.rs
Previously permissions were always prompted, regardless of how many of
them were actually requested by the extension. This patch fixes that and
only prints the requests when there are actual permissions being
requested.
The permission output is also reformatted a bit to distinguish the
important parts of the output more clearly from the prose describing
their purpose.
To ensure the user is correctly informed about what choice he should
make if he's incapable of answering the prompt, "no" has also been
selected and marked as the default.
Before:
```
The `x3` extension requires the following permissions:
Read from the following paths:
Write to the following paths:
Run the following commands:
bash
zsh
Access the following domains:
phylum.io
Do you accept? [y/n]
```
After:
Note that `Run` and …
=> Fix permission prompting behavior

cli/src/commands/extensions/extension.rs
This sets the loglevel when running extensions to `LevelFilter::Off`,
which should prevent us from messing with the extension's console output
when not explicitly requested.
Closes #517.
=> Disable logging in extensions

cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/extension_api.ts
Before this patch, the `get_job_status` extension API would fall back to
the project ID when no job ID was specified, however the project ID is
not a valid job ID.
Since there's no reasonable default for us to pick, this patch instead
switches the job ID parameter to be mandatory.
This also removes the alias for "current" as the latest job ID, since
this API changed due to the request manager removal.
=> Make job ID mandatory in job status extension api

cli/src/app.rs
This resolves a regression in CLI version 3.6.0 where the Job ID was
accidentally marked as a required argument for the command. Fixes #524
=> Don't require Job ID for `phylum history` command

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/project.rs
Now that the endpoint to delete projects [is exposed](https://api.staging.phylum.io/api/v0/swagger/index.html#/Projects/projects_delete_project) (in staging at least), we can go ahead and implement the `phylum project delete` command.
=> Add `phylum project delete` command

cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/tests/extensions.rs
Since `phylum extension new` is likely the most common way users will
create new extensions, it should not be possible to creat invalid
extensions with it.
This patch validates the extension name during creation, refusing to
create one with an invalid name.
Closes #515.
=> Validate extension name in `phylum extension new`

cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs
Since most extensions will likely follow the suggestions made by the
skeleton created from `phylum extension new`, it's unnecessary to have
the entry_point specified explicitly in the extension manifest.
Closes #509.
=> Use main.ts as default entry_point

cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/src/deno.rs
Before this patch, the generated `PhylumExt.toml` manifest would always
contain an empty `[permissions]` section, which did not do anything
other than cluttering the manifest.
By making the permission section itself optional, it will never be
serialized into the generated toml file.
Closes #532.
=> Remove `[permissions]` from generated manifest

cli/src/commands/extensions/extension.rs, cli/tests/extensions/permissions.rs, docs/extensions/example.md
This patch checks for JS runtime execution errors and truncates the
Deno-specific suffix from permission errors, if it is present.
Closes #520.
=> Remove Deno CLI flag from permission error output

cli/src/commands/extensions/api.rs, cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/src/commands/extensions/permissions.rs, cli/src/deno.rs, cli/tests/common/mod.rs, cli/tests/end_to_end/extension.rs, cli/tests/fixtures/extensions/api/PhylumExt.toml
Since some of our own APIs access user-defined files and return parts of
these files, it's necessary to validate the access against the
extension's permissions.
Closes #523.
=> Validate file permissions in Phylum extension API

cli/src/summarize.rs
Since the user ID is currently not present in the APIs response anyway,
the field was removed from the output.
Closes #396.
=> Remove user ID from analysis output

CHANGELOG, Cargo.lock, cli/Cargo.toml
The next release!
Release-Version: v3.7.0
Release-Summary: ARM64 Linux support and Maven workspaces
=> Bump to v3.7.0 - ARM64 Linux support and Maven workspaces

Cargo.lock
Now that phylum-dev/phylum-types#27 is merged, we can finally remove uuid 0.8.2 🎉
=> Bump phylum-types and remove uuid 0.8.2

.github/workflows/release.yml
The `docs` command is expecting a directory as parameter, but we were
incorrectly passing all documentation files.
=> Fix CI release readme release process

docs/command_line_tool/phylum_extension.md
Correcting the `category` for this file so it goes to the `Command Line Tool` category (currently pointing at `Knowledge Base`). This file remains `hidden` until it is appropriate to expose it in our user docs. I checked the other "extension" related docs in this folder and they were set appropriately 👍
=> docs: Category correction to phylum_extension.md

cli/src/commands/extensions/api.rs, cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/src/commands/extensions/state.rs, cli/src/deno.rs
This fixes an issue where clippy would complain about references being
held across await points in our async extension APIs.
The underlying issue is that mutable access to our `RefCell` state would
panic when another asynchronous method held a reference to it across
await points.
This patch does not fix the underlying issue, but instead provides
guidelines to help developers avoid the pitfalls with mutable references
in asynchronous code.
=> Fix clippy ref warning in extension API

cli/src/commands/extensions/api.rs, cli/src/extension_api.ts, cli/tests/end_to_end/extension.rs, cli/tests/fixtures/extensions/api/main.ts
This patch changes the `analyze` extension API to take in the package
type and a list of packages, rather than a lockfile path. This comes
with several advantages.
Since we don't do any file I/O anymore, we don't have to worry about
checking for permissions. The lockfile type also doesn't need to be
known to us, instead people can just freely submit any packages for
their ecosystem.
This new API provides a much more composable interface which allows
future extension developers to easily integrate the CLI into their
custom workflows even with custom proprietary lockfiles.
The previous usecase of just analyzing a known lockfile without the
extension having to parse it themselves is still covered by plumbing the
`parseLockfile` API's output into `analyze`.
=> Use package list parameter for analyze API

cli/src/commands/extensions/extension.rs, cli/src/commands/mod.rs, cli/src/deno.rs, cli/src/fmt_deno_error.rs, cli/src/lib.rs
This patch takes the error formatting from Deno's CLI and applies it to
our extension errors, allowing for a richer JavaScript error responds
which hopefully will help developers with debugging their extensions.
Closes #570.
=> Improve extension error formatting

Cargo.lock, cli/Cargo.toml, cli/src/lockfiles/javascript.rs
This fixes the issue in our automated weekly dependency updates which
caused them not to build without intervention.
=> Bump dependency major versions

cli/src/deno.rs, cli/tests/extensions/permissions.rs, docs/extensions/extension_api.md
This removes the JavaScript `Deno.permissions.request` operation to
prevent extension developers from sidestepping our manifest permission
system.
=> Remove Deno's built-in permission prompts

cli/src/commands/extensions/api.rs, cli/src/commands/extensions/state.rs, cli/src/deno.rs
This modifies the extension API's permission validation checks to rely
on Deno's internal `check` method rather than trying to validate
permissions ourselves.
Closes #579.
=> Validate permissions using Deno's `check`

Cargo.lock, cli/src/config.rs
This PR updates the configuration loading code such that if the offline access token is an empty string it gets replaced with `None`. There is already code in a few places that checks whether we have an access token by checking if the access token is `None`, but in certain situations it's possible to set the access token to `Some("")` (I think commonly this happens by setting the environment variable to an empty string), which gets past all the checks and results in an "invalid refresh token" error from the authentication server. After this PR, if the refresh token is empty string, CLI will behave as if the refresh token were not configured at all, displaying a message in some situations and beginning authentication in others.
I think this resolves will resolve the "invalid refresh token" …
=> ignore empty refresh token from environment

docs/extensions/extension_example.md, extensions/duplicates/PhylumExt.toml, extensions/duplicates/main.ts
This updates the existing extension example documentation to take the
new permission system into account.
It also updates to the latest `parseLockfile` return type.
Closes #580.
=> Update extension example documentation

cli/src/api/mod.rs, cli/src/bin/phylum.rs, cli/tests/extensions/permissions.rs
Use the `description` from API as the error message when available. Also clean up double printing and excessive language.
=> Better error messages

cli/src/commands/extensions/mod.rs, cli/src/config.rs, cli/src/deno.rs, cli/tests/extensions/mod.rs, cli/tests/extensions/module_loader.rs, cli/tests/fixtures/extensions/module-import/fail-local/main.ts
This patch fixes an issue with `phylum extension run`, where relative
paths were not accepted as parameter.
To ensure that our module loader's restriction to only load from within
the extension's directory still works properly, all paths are not
canonicalized in the module loader. This means we do not need to check
for symlinks explicitly.
Closes #586.
=> Fix running extensions with relative paths

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/bin/phylum.rs, cli/src/commands/auth.rs
Fix #594 by restoring error trace output and removing the unhelpful `"Error creating client"` context.
```
❯ phylum auth status
❗ Error: Error creating client
```
```
❯ phylum auth status
❗ Error: error sending request for url (https://api.staging.phylum.io/api/v0/.well-known/openid-configuration): operation timed out
Caused by:
operation timed out
```
=> Restore error trace output

.github/workflows/release.yml
The musl and arm targets have been temporarily disabled in order to get
an automated release out that contains the working target artifacts.
The `phylum-ci` Docker image trigger was also disabled so as not to affect the integrations that are already working.
This workflow can be viewed [here, for the branch](https://github.com/phylum-dev/cli/actions/runs/2820468964). If it works there as expected, then it should be merged to `main` for the `v3.8.0` release (or `v3.8.0-rc0` release) and then reverted after a solution is found for automating the MUSL and ARM64 release targets and artifacts in CI.
=> ci: disable failing targets in release workflow

.github/workflows/release.yml, docs/command_line_tool/alternate_install.md
This change matches the language marketing has approved. A check of `phylum-ci` revealed that the signature is verified but the trusted comment content is not (it just needs to exist).
=> docs: update artifact signature and docs to match current tagline

.github/workflows/release.yml, Cargo.lock, cli/Cargo.toml
In 15c2a5a, all features were removed from the `zip` dependency, causing
the `phylum update` command to break since it was no longer able to
unzip the release assets.
This adds back all the default zip compression feature flags, while
keeping the `aes-crypto` feature disabled, which caused the original
dependency conflicts.
Closes #610.
=> Fix `phylum update`

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/yarn.lock
This resolves an issue with the yarn parser which would cause the
parsing to fail when encountering a link dependency.
This is fixed by accepting link dependencies as a dependency that is
ignored by Phylum. All other unknown dependency types will still cause a
failure.
Closes #598.
=> Fix link dependencies in yarn parser

cli/src/api/endpoints.rs, cli/src/api/mod.rs
The `/api/v0/data/jobs` endpoint is adding support for the more correct `POST` method. The CLI should update to match as soon as this method is available in prod.
=> Use POST for job submission instead of PUT

cli/src/bin/phylum.rs, cli/src/commands/extensions/mod.rs, cli/tests/extensions/mod.rs
Closes #605.
Adds a hard-coded handling of the `-h` and `--help` flags and `help` subcommand when those are supplied as first parameter to `phylum extension run`.
=> Handle `-h`, `--help` and `help` as first argument of `extension run`

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/package-lock.json
This resolves an issue with the v7+ package-lock.json parser where
remote git dependencies would be submitted as npm packages, causing the
analysis to never complete.
This patch uses the `resolved` field instead of `version` for all
packages that do not resolve to the `registry.npmjs.org` domain.
This leaves the v6 lockfile parser unaffected, since backporting
shouldn't be necessary given that most people should move on to v7+
automatically over time.
Closes #622.
=> Add git dependency support to package-lock.json

cli/src/lockfiles/java.rs, cli/src/lockfiles/parsers/gradle_dep.rs, cli/src/lockfiles/parsers/mod.rs, cli/tests/fixtures/gradle.lockfile
This resolves an issue in the gradle parser where dependencies without a
trailing `=classpath` were just ignored.
=> Fix parsing gradle lockfile without classpath

cli/src/api/mod.rs, cli/src/commands/auth.rs, cli/src/commands/extensions/api.rs, cli/src/config.rs, cli/src/test.rs, cli/tests/common.rs, cli/tests/config.rs
This fixes an issue with the CLI where the config's token would be
overwritten whenever using the PHYLUM_API_KEY environment variable.
Instead of overwriting the config based on what is stored in the
environment variable, the variable and config value are now tracked
separately, always writing the config's value whenever a write is
instructed and returning the environment variable (if present) when
reading from it.
Closes #582.
=> Fix PHYLUM_API_KEY overwriting config token

tag.sh
This fixes an issue with the `tag.sh` script where it was incapable of
tagging releases from a branch with a name identical to the tag name
itself.
=> Fix release tagging from branches

.github/workflows/release.yml, README.md, cli/src/install.sh, cli/src/update/unix.rs, scripts/phylum-init.sh
This PR changes the installation scripts and the `README` to refer to the new `gnu` based binaries.
Opening as draft PR to request feedback on wording and alternative strategies.
Closes #426.
=> Transitioning away from `musl`

.github/workflows/release.yml
This adds glibc releases as *-unknown-linux-musl to the release archives
to allow older versions to seamlessly transition to the new glibc
executables.
This does NOT provide a musl version, the archives are still glibc
executables and this will only help with updates on systems that support
both musl AND glibc.
=> Add -musl shims to release archives

cli/src/bin/phylum.rs, cli/src/commands/auth.rs, cli/src/commands/extensions/mod.rs, cli/src/print.rs
This resolves an issue for the `phylum extension run` subcommand where
invocations of `help`/`--help`/`-h` would cause it to print the `phylum`
help, rather than the `phylum extension run` help.
The patch also cleans up some unnecessary edge-case handling of
scenarios that are impossible to hit.
Closes #639.
=> Fix incorrect help for `phylum extension run -h`

cli/src/commands/extensions/api.rs, cli/src/extension_api.ts, cli/tests/end_to_end/extension.rs
None of our extensions use the `getProjectDetails()` function and it is based on a deprecated endpoint. This patch removes it from the extension API as a simple way to fix #642. We could deprecate it instead, but I am doubtful that it provides much, if any, value and I do not want the initial release of extensions to include a deprecated function.
New functions will be added to the extension API in #644 and #645 to handle any use cases that may exist involving "project details"
=> Remove getProjectDetails() function from extension API

.github/workflows/release.yml
This adds glibc releases as `*-unknown-linux-musl` to the release
archives at an earlier step in the release workflow to allow older
versions to seamlessly transition to the new glibc executables.
The previous shim renamed outer zip artifacts without accounting for
the directory naming within the archive, causing the update to fail to
find the `install.sh` script within the extracted contents.
This fix still does NOT provide a musl version; the archives are still
glibc executables. This will only help with updates on systems that
support both musl AND glibc (e.g., WSL on Windows).
=> fix: update shim for musl to gnu is broken

cli/src/commands/extensions/api.rs, cli/src/extension_api.ts, cli/tests/end_to_end/extension.rs
This patch adds some additional APIs to query for general project
information. This includes querying the linked project offline, the
user's groups and the user's projects.
Closes #645.
Closes #644.
=> Add project extension APIs

Cargo.lock, cli/Cargo.toml
This adds the native/WebPKI features to `reqwest`, allowing us to pull
certificates managed by the user's operating system.
Closes #651.
=> Add native/WebPKI TLS features

docs/command_line_tool/phylum_analyze.md, docs/knowledge_base/analyzing-dependencies.md
The existing documentation still pointed to the `pom.xml` as supported
format for Maven. This has been changed to correctly indicate we only
support the `effective-pom.xml` format.
=> Update Maven pom documentation

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v3.9.0
Release-Summary: Add support for native certificate store
=> Bump to v3.9.0 - Add support for native certificate store

extensions/npm/main.ts, extensions/yarn/main.ts
This fixes an issues with some of the ecosystem extensions, where they
would continue running even after an error was encountered.
Closes #658.
=> Fix extensions continuing on error

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/package-lock.json
This fixes an issue with npm package-lock.json dependencies where
packages placed in other dependencies' node_modules folders were not
correctly identified.
Instead of parsing `node_modules/dep/node_modules/dep2` as
`dep/node_modules/dep2`, it is now identified properly as `dep2`.
This kind of package structure can occur when dependencies exist
multiple times in the dependency graph. Placing it as a child of a
specific dependency is npm's way to keep multiple package versions,
since the directory on the root does not have the version as part of its
name. This is why both versions must be submitted.
Closes #662.
=> Fix parsing of nested package-lock dependencies

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v3.9.1
Release-Summary: Fix package-lock.json parsing
=> Bump to v3.9.1 - Fix package-lock.json parsing

cli/src/api/mod.rs, cli/src/app.rs, cli/src/auth/oidc.rs, cli/src/update/unix.rs
This patch adds a user-agent header to our HTTP requests. I chose to use the `git-version` (i.e., the same thing output by `phylum version`) for this in order to properly identify RC versions and local builds.
=> Send an appropriate User-Agent header

README.md, docs/extensions/extension_howto.md
Adding links for the how-to page
CC: @ambray
=> docs: Add extension how-to links

cli/src/config.rs, cli/src/install.sh
The migration to XDG directories was months ago, so it should now be safe to remove the migration code.
=> Remove XDG migration code

cli/src/commands/extensions/extension.rs
The extension name error message pointed out `_` as a legal character, however the regex itself did not allow for this character.
To ensure extension naming is consistent, the `_` is removed from the error and only `-` is allowed.
=> Fix extension name regex

CONTRIBUTING.md, LICENSE, README.md, cli/Cargo.toml, cli/src/bin/phylum.rs, docs/command_line_tool/quickstart.md
The license file itself was changed. Then, references to it were added to both the README and CONTRIBUTING documents. Finally, the output of the `phylum version` command was changed to include the origin and legal status, as recommended by the [GNU Standard](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html).
Closes #688
Output with the changes from this PR:
=> chore: change the license from MIT to GPLv3+

cli/src/lockfiles/javascript.rs, cli/tests/fixtures/yarn.lock
This fixes an issue where the yarn parser would panic when a resolver was encountered that uses local filesystem resolution without symlinks.
Closes #689.
=> Fix local yarn filesystem dependencies

.github/workflows/release.yml, cli/src/commands/extensions/extension.rs, cli/src/commands/extensions/mod.rs, cli/src/install.sh, cli/src/print.rs, cli/tests/extensions/mod.rs, docs/extensions/extension_overview.md, extensions/npm/README.md, extensions/poetry/README.md, extensions/poetry/fixtures/pyproject.toml, extensions/yarn/README.md
Close #641
An example of running the installer after this change:
```
❯ ./install.sh                                         
phylum-cli installer
OK Copied completions to /Users/kyle/.local/share/phylum/completions
Installing extension npm...
✅ Extension npm already installed, nothing to do
Installing extension poetry...
Another version of the 'poetry' extension is already installed. Overwrite? no
❗ Error: install aborted
Installing extension yarn...
✅ Extension yarn installed successfully
OK Installed default extensions
OK Completions are enabled for bash.
OK Completions are enabled for zsh.
OK Successfully installed phylum.
Source your /Users/kyle/.zshrc file, add /Users/kyle/.local/bin to your $PATH variable, or
log in to a new terminal in order to make `phylum` available.
```
=> Include pre-installed extensions

cli/src/commands/extensions/mod.rs
This patch prepends the relative path prefix (`./`) to all relative paths that do not already have it when printing the installation suggestion after extension creation.
The change is necessary since relative paths without `./` prefix cannot be installed, since they're reserved for installing extensions from the marketplace in the future.
Closes #710.
=> Add `./` prefix to extension install suggestions

.github/workflows/test.yml
Github Actions don't allow access to secrets when triggered by a `pull_request` event from a fork. This PR adds a condition to skip this test so that it does not fail or hang (like we have seen in #714)
=> Skip end-to-end test for external PRs

.github/workflows/test.yml, cli/src/app.rs
This fixes a regression introduced in the clap 4 update (925de7d) which caused the help output to be sorted in order of definition rather than alphabetically.
Fixes #727.
=> Fix help output sort order

.github/workflows/test.yml
Attempting to make the cache smaller in #733 was a failure. Maybe we can speed up the tests in other ways and remove caching altogether.
=> Optimize test workflows without caching

lockfile/src/javascript.rs, tests/fixtures/package-lock.json
This fixes an issue with the NPM `package-lock.json` parser which would cause parsing failure when encountering a bundled dependency in the lockfile.
These bundled dependencies are filtered out, since their content is already analyzed when analyzing the root of the dependency bundle.
Closes #748.
=> Fix NPM dependency bundling

CHANGELOG, Cargo.lock, cli/Cargo.toml, cli/src/lockfiles/javascript.rs, cli/tests/fixtures/package-lock.json
Release-Version: v3.10.1
Release-Summary: Fix NPM dependency bundling
=> Bump to v3.10.1 - Fix NPM dependency bundling

cli/src/app.rs, cli/src/commands/jobs.rs
This fixes a regression introduced in 8748152 where the CLI would panic when running the jobs/analyze subcommands since these had CLI arguments conflicting with the new global `verbose` flag.
=> Fix verbosity errors

cli/src/app.rs, cli/src/commands/jobs.rs
This removes the mention of `current` as a valid option from the `phylum history` command and also improves its error message to more clearly indicate why the operation failed when something other than a job ID was passed as argument.
Closes #751.
=> Improve `phylum history` UUID error message

cli/src/api/mod.rs, cli/src/bin/phylum.rs, cli/src/commands/auth.rs, cli/src/config.rs, cli/src/test.rs, cli/tests/common.rs, cli/tests/config.rs
This resolves an issue with the `--no-check-certificate` CLI option which would cause the `ignore_certs` flag to be permanently changed to `true` in the user's Phylum configuration file.
Closes #664.
=> Fix CLI certificate override modifying config

docs/command_line_tool/phylum_history.md
Remove the use of `current` in the docs for `phylum history` based on this PR https://github.com/phylum-dev/cli/pull/753
=> docs: Remove `current` from phylum_history.md

Cargo.lock, cli/Cargo.toml, cli/src/commands/extensions/api.rs, cli/src/commands/extensions/permissions.rs, cli/tests/extensions/mod.rs
This makes use of the latest commits in birdcage to add sandboxing of environment variables, blocking all environment variable access by default.
The environment variable sandboxing will not cause any errors, but instead just removes all restricted variables from the environment making them invisible to the child process.
The existing `run_sandboxed` code has been rewritten to use a manual `fork` instead, since `pre_exec` cannot access environment variables. This additional fork shim will automatically forward STDIN/STDOUT/STDERR based on the process setup in the extension's `runSandboxed` call.
Closes #703.
=> Add environment variable sandboxing

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v3.11.0
Release-Summary: Extension API: Sandbox processes, create and delete projects
=> Bump to v3.11.0

cli/src/commands/extensions/mod.rs
While the current HEAD does prompt for accepting the permissions when
only an environment variable exception is requested, it does not
actually print to the user which environment variable access it needs.
This patch fixes this issue by adding another prompt for the environment
variable permissions.
=> Fix environment variable permission prompting

cli/src/app.rs, docs/command_line_tool/phylum_analyze.md, docs/command_line_tool/phylum_history.md, docs/command_line_tool/phylum_package.md
There are a few instances where a long option is provided without a short option and vice versa. This patch attempts to clean those up to be more consistent throughout the CLI interface.
* Add the short form `-f` to go with the long form option `--filter`
* Add the long form `--label` to go with the short form `-l`
* Remove the unused `--low-priority` option from the `batch` subcommand
* Update the docs to reflect the changes
=> docs: clean up options

cli/src/commands/extensions/permissions.rs
Since users might rely on executables in their $PATH being accessible for extensions, an exception was added to the default sandbox allowing for access to $PATH by default.
The $PATH is still cleared when using the strict sandboxing mode.
=> Add default sandbox exception for $PATH

cli/src/commands/packages.rs
Fix the `--package-type` option by avoiding the call to `get_flag` (since this option is not a flag).
=> Fix --package-type option

lockfile/src/lib.rs, lockfile/src/parsers/gradle_dep.rs, lockfile/src/parsers/mod.rs, tests/fixtures/gradle.lockfile
Previously the Gradle parser was **very** permissive, so much so that
some of our non-Gradle test lockfiles were accepted as valid Gradle
lockfiles.
This patch rewrites the Gradle parser while attempting to be as strict
as possible. Running against our lockfiles in tests/fixtures now shows
that all parsers can only parse the lockfiles in their specific format.
Closes #754.
=> Improve strictness of Gradle parser

cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs
There were two places where we might print to stdout when running `phylum analyze --json`. One of them is printing the Job ID. This patch avoids printing in that case. The other is identifying a previously unknown lockfile. This patch sends that output to stderr.
Closes #769
=> Avoid stdout when run with `--json`

cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/extensions/api.rs, cli/src/commands/mod.rs, cli/src/commands/sandbox.rs, cli/tests/common.rs, cli/tests/extensions/mod.rs, cli/tests/extensions/module_loader.rs, cli/tests/extensions/permissions.rs, cli/tests/integration.rs, cli/tests/sandbox.rs
This fixes any potential issues with setting up our sandboxing
environment in `pre_exec` or after a `fork` by adding a new `phylum
sandbox` subcommand. Using this subcommand we can simply re-execute
`phylum` with the appropriate arguments to setup a sandboxing
environment.
Closes #763.
=> Re-execute phylum for sandboxing extensions

.github/workflows/test.yml, .prettierignore, CONTRIBUTING.md, cli/src/extension_api.ts, extensions/duplicates/main.ts, extensions/find-permissions/main.ts, extensions/npm/main.ts, extensions/poetry/main.ts, extensions/poetry/tests.ts, extensions/yarn/main.ts
Closes #704.
This PR adds a job for checking extensions' formatting with [prettier](https://prettier.io/).
`prettier` is opinionated and requires no configuration to be run.
In this PR, the only manual modifications are in the `test.yml` workflow; the remainder of the diffs derive from applying the formatting.
=> `prettier` format checks

cli/src/bin/phylum.rs, cli/src/update/unix.rs, cli/src/update/unsupported.rs
Closes #665.
The HTTP get functions have been refactored as methods of `ApplicationUpdater` in order to avoid passing around too many `ignore_certs: bool` parameters.
=> Added ignore certs flag

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v3.12.0
Release-Summary: Permissions extension API
=> Bump to v3.12.0 - Permissions extension API

cli/src/commands/jobs.rs
This is a continuation of #773, to resolve #769
Behavior before this change:
---
Behavior after this change:
=> fix: avoid stdout when run with --json

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v3.12.1
Release-Summary: Fix to avoid stdout when run with `--json`
=> Bump to v3.12.1 - Fix to avoid stdout when run with `--json`

docs/knowledge_base/analyzing-dependencies.md, lockfile/src/lib.rs, lockfile/src/python.rs, tests/fixtures/poetry_v2.lock
This adds tests and documentation for supporting v2 of the poetry lockfile.
There are no changes to our parser, since none of the v2 changes affect the packages or their versions.
Closes #761.
=> Add poetry lockfile v2 support

extensions/npm/main.ts
Updates the read permissions to limit access to disk from the npm extension. Also adds the `--ignore-scripts` to the lock file generation.
=> Add ignore scripts when updating package-lock.json

extensions/yarn/PhylumExt.toml, extensions/yarn/main.ts
Adds cache directory to allowed directories for Yarn on MacOS.
=> Add cache directory for macos

cli/src/app.rs, cli/src/bin/phylum.rs
Fixes #782 by putting `phylum update` behind the "selfmanage" feature flag.
=> Require "selfmanage" feature flag for `phylum update`

cli/src/app.rs, cli/src/auth/oidc.rs, cli/src/commands/auth.rs, cli/src/commands/extensions/permissions.rs, cli/tests/sandbox.rs, docs/command_line_tool/phylum_auth.md, docs/command_line_tool/phylum_auth_set_token.md, lockfile/src/lib.rs
This patch adds a command to set the token in the config file. This provides an alternative to `phylum auth login` provided you can get the token from some other place. The other place may be `phylum auth token` from another machine or, in the future, we may support copying the token directly from the web UI.
=> `phylum auth set-token`

cli/src/app.rs, cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, docs/command_line_tool/phylum_analyze.md
This patch unifies the lockfile parser and enables passing the desired
lockfile for all subcommands requiring lockfile parsing as an optional
parameter.
Closes #794.
=> Add `--lockfile-type` option to `phylum analyze`

cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/init.rs, cli/src/commands/mod.rs, cli/src/commands/project.rs, cli/src/histogram.rs, cli/src/prompt.rs, docs/command_line_tool/phylum_init.md
This adds a new subcommand for setting up a new Phylum project.
Currently this command will only negotiate the desired project name and corresponding group, but further information like lockfile can be detected in the future.
Project and group can either be specified directly in the CLI, or specified interactively.
The user is not prompted for a group name when passing the project name on the CLI, to enable non-interactive usage without passing extra CLI flags. So in this scenario a group must be specified with `--group`.
Closes #795.
=> Add `phylum init` subcommand

CODE_OF_CONDUCT.md, SECURITY.md
Add code of conduct and security policy in order to meet the community standards for a public repository.
=> Add code of conduct and security policy

cli/src/commands/jobs.rs
The `phylum batch` command was not correctly handling the `--type` parameter due to a regression in #721. This patch fixes that issue
=> Fix `phylum batch` command

Cargo.lock, cli/Cargo.toml, cli/src/app.rs, cli/src/commands/extensions/api.rs, cli/src/commands/init.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/src/commands/project.rs, cli/src/config.rs, docs/command_line_tool/phylum_analyze.md, docs/command_line_tool/phylum_parse.md, xtask/src/main.rs
This patch extends the existing .phylum_project with two new optional
fields: `lockfile` and `lockfile_type`.
When the `lockfile` type is present in the .phylum_project file and no
lockfile override is specified on the CLI, then the project file from
the .phylum_project file will be used with the lockfile type specified
in the same file.
If the lockfile type is specified on the CLI without the lockfile being
specified, it will be ignored.
The lockfile name and type can be set when running `phylum init`, either
by passing `--lockfile` and (optionally) `--lockfile-type`, or by
specifying them interactively.
Closes https://github.com/phylum-dev/cli/issues/793.
=> Add lockfile path and type to .phylum_project

docs/command_line_tool/phylum_init.md
The d4d70a5 patch introduced changes to the `phylum init` CLI subcommand which were not appropriately documented in our website's documentation.
This patch fixes this and updates the docs to be up to date with the current `phylum init` command and its arguments.
=> Add lockfile CLI docs for `phylum init`

.github/workflows/release.yml, docs/command_line_tool/alternate_install.md
Remove `.minisig` files from future releases and close #738 
After a `grep -r minisig .`, I realized that I forgot to update the alternate install docs during the 2517c58 patch. So I have fixed that here as well.
=> Remove minisign artifacts

.github/workflows/cargo-update.yml, .github/workflows/release.yml
This patch contains multiple changes that allow us to protect the `OPENSSL_KEY` and `GH_RELEASE_PAT` secrets by putting them in a GitHub environment named `release`.
Additional details for each change can be found in the respective commit messages.
=> Use release environment to protect repo secrets

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/group.rs, cli/src/format.rs, docs/command_line_tool/phylum_group.md, docs/command_line_tool/phylum_group_member.md, docs/command_line_tool/phylum_group_member_add.md, docs/command_line_tool/phylum_group_member_list.md, docs/command_line_tool/phylum_group_member_remove.md, xtask/src/main.rs
This patch adds the new `phylum group members` subcommand which has the additional `list`/`add`/`remove` subcommands. These allow managing and inspecting the users which are part of a group.
The `members`/`list` commands behave similarly to all our other commands, doing the same thing and just listing all members that are part of the specified group.
The group parameter is a required parameter for the `members` subcommand, which allows clap to provide helpful messages guiding the user to specify it in the correct location, rather than having to handle all possible locations internally.
Closes #810.
=> Add group member management subcommands

cli/src/app.rs
The cargo fallback is used when no git information is present (like when the source tarball is downloaded instead of cloning the repo).
The + suffix was chosen to indicate "something after version X".  For example, this would currently show "v3.12.1+" as the version, which is accurate.
This fixes #818. After this change, builds outside of git (including Homebrew) will look like so:
```
❯ phylum --version
phylum 3.12.1+
❯ phylum version  
✅ phylum (Version 3.12.1+)
Copyright (C) 2022  Phylum, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
=> Use plus suffix for git_version's cargo fallback

LICENSE
While not necessary, this fills out the copyright information in the license. This could help point out Phylum's involvement should the license ever get packaged with another application.
The main argument for adding this additional information however is consistency with phylum-dev/birdcage. This way all of our licenses have the same structure.
=> Fill out copyright notice in license templates

lockfile/src/javascript.rs, tests/fixtures/package-lock.json
This changes the v7+ package-lock.json parser to accept third-party registries and submit their packages pretending they are hosted on npmjs.org.
Since the v6 parser has the same behavior, it should allow for a more consistent user experience while still providing as good of an analysis as we can get with the information we have.
=> Fix package-lock parsing with 3rd-party registries

.github/workflows/cargo-update.yml
In #816 (and #817), I tried to change the `cargo-update.yml` workflow to use `GITHUB_TOKEN` instead of a PAT. That was a mistake. The workflow_dispatch trigger does not properly connect to the opened PR.
This patch reverts the 8f4f7e5 and 82fb0a3 changes to that workflow. Other changes made in those commits (namely, to the `release.yml` workflow) are not reverted.
=> Revert to using a PAT for cargo update

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v4.0.0
Release-Summary: Extensions are sandboxed by default
=> Bump to v4.0.0 - Extensions are sandboxed by default

.github/workflows/release.yml, .github/workflows/test.yml
In order to drop the glibc requirement for our binaries, this patch downgrades our linux builders to ubuntu 20.04
=> Downgrade linux builder to 20.04

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v4.0.1
Release-Summary: Use a lower version of GLIBC
=> Bump to v4.0.1 - Use a lower version of GLIBC

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/group.rs, cli/src/commands/init.rs, cli/src/commands/mod.rs, docs/command_line_tool/phylum_group.md, docs/command_line_tool/phylum_group_transfer.md
This patch adds support for the new API endpoint to transfer group ownership between users.
To ensure that groups are not accidentally transferred to incorrect users and since the operation cannot be reverted easily, extra precautions are taken in the form of a confirmation prompt.
Closes #832.
=> Add `phylum group transfer` subcommand

cli/src/commands/init.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/src/commands/project.rs, cli/src/config.rs
Since the lockfile was specified as a relative path in the project lockfile, an analysis would fail when the analysis was started from a child directory of the Phylum project directory.
To ensure that analysis will work in any of the child directories, a root path of the project is now stored in the config on load and the lockfile location is determined based on that root directory whenever it is required.
While an absolute path to the lockfile might work temporarily, it was intentionally avoided as a solution since it would break when the project is moved to a different location or shared between different systems.
Closes #843.
=> Fix subdir analysis without lockfile parameter

cli/src/app.rs, cli/src/commands/parse.rs, docs/command_line_tool/phylum_init.md
This adds restrictions on the allowed parameters that can be passed to the lockfile types parameter on `phylum init` to clap, allowing for proper documentation and feedback when an invalid value is specified.
Closes #847.
=> Add possible values to `phylum init -t`

cli/src/commands/extensions/permissions.rs, cli/src/commands/init.rs, cli/src/commands/project.rs
This reorders the steps in the project initialization for the `phylum init` command, to improve user experience with the command.
Instead of trying to create or link to the project before prompting for the lockfile path and type, all API operations are now moved to the end after the user has finished his inputs. This way looking can go on in the background without users waiting for long-running API calls to complete.
Closes #841.
=> Reorder project initialization

.github/workflows/release.yml, .github/workflows/test.yml
This removes the unnecessary usage of actions-rs/toolchain and actions-rs/cargo in favor of using rustup and cargo directly.
The patch should also ensure that when running with a specific toolchain version (like `stable`), that this version is always up to date.
=> Remove actions-rs GitHub actions

cli/src/commands/init.rs, cli/src/config.rs
Previously, `phylum init` would query if the project should be overwritten when a parent project contained a project file already.
Since we do not actually overwrite any project files outside of the current directory, and since having nested Phylum projects is perfectly valid, a warning is now only emitted when there's already a Phylum project file in the current directory.
Closes #839.
=> Ignore parent directory projects for `phylum init`

Cargo.lock, cli/Cargo.toml
Since we have full control over the compression algorithm used to create the Phylum executable, it is not necessary to support multiple algorithms.
The only necessary algorithm is deflate, which is what our zip files are compressed with by default.
This should improve compile times, since zstd-sys compilation in CI takes over 2 minutes.
=> Remove unused zip compression algorithms

extensions/npm/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
This moves the check for required intervention of the ecosystem extensions to the start of each extension, making sure that the behavior of commands is completely unchanged unless we explicitly want to intercept a command.
=> Skip backup for non-intercepted ecosystem commands

extensions/npm/main.ts, extensions/poetry/PhylumExt.toml, extensions/poetry/main.ts, extensions/yarn/PhylumExt.toml, extensions/yarn/main.ts
This patch traverses up to 32 directories upwards to find the root of a
potential ecosystem project. This way the ecosystem commands should
still work when inside a nested directory in a project.
---
Ecosystem extension subcommands which aren't intercepted by Phylum could
do theoretically anything and at the same time aren't particularly at
risk. As a result it is more reliable to just not sandbox these and use
normal `Deno.run` instead.
=> Traverse directories to find ecosystem root

cli/src/commands/init.rs
Currently when running `phylum init`, the user is first asked if they want to use a group and then forced to enter a group name. While it has documented none sa the default, it is not possible to just press enter to use that default. As a result users are forced to abort and restart `phylum init` if they accidentally landed here.
This patch combines the prompt for entering a group and the actual group name input into a single prompt. This way the user is never "stuck" in a state where he has to Ctrl+C out of. This also makes it quicker to enter a group should it be desired.
=> Fix group prompt during `phylum init`

cli/src/extension_api.ts
This patch switches the doc comments in our extension API definition file to JSDoc style comments. This change allows our docs to be consumed by normal deno tools for generating docs.
To see an example of these docs rendered, view them here on [doc.deno.land](https://doc.deno.land/https://raw.githubusercontent.com/phylum-dev/cli/jsdoc/cli/src/extension_api.ts/~/PhylumApi).
=> Use JSDoc comments in extension API

cli/src/config.rs
This patch fixes the warning emitted by `phylum init` when there is no config file in the current directory.
=> Don't warn about config search if we didn't recurse

cli/src/extension_api.ts
Update extension_api.ts to use the types from lib.deno_core.d.ts and avoid any.
Thanks to this update, I discovered that `Deno.core.opSync` is no longer supported and has been [removed from deno_core]
[removed from deno_core]: https://github.com/denoland/deno/pull/16379
=> Use lib.deno_core.d.ts types

cli/src/commands/extensions/api.rs, cli/src/commands/extensions/permissions.rs, cli/src/extension_api.ts, cli/tests/common.rs, cli/tests/end_to_end/extension.rs, docs/extensions/extension_overview.md, docs/extensions/extension_rest_api.md
This patch adds some new abstractions to the extension API which make it easier for extension authors to make requests directly to Phylum's REST API.
To ensure people can figure out how they're supposed to use these new functions, the functionality has also been documented in our extension documentation.
Closes #863.
Closes #862.
---
Outstanding questions before undraft:
=> Add extension helpers for direct API requests

cli/src/api/mod.rs, cli/src/app.rs, cli/src/auth/oidc.rs, cli/src/auth/server.rs, cli/src/commands/auth.rs, docs/command_line_tool/phylum_auth_login.md
This patch adds support for `phylum auth login --reauth` to force reauthentication.
There seems to be an issue with the way Keycloak displays informational messages. This isn't something that can be fixed in the CLI so we'll have to take care of it separately. Maybe @janasheehan can take a look. Here is how to reproduce:
1. Login to [staging](https://app.staging.phylum.io/)
2. Run `phylum auth login -r` from this branch. Or just click [this link](https://login.staging.phylum.io/realms/phylum/protocol/openid-connect/auth?client_id=phylum_cli&code_challenge=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A12345%2F&response_type=code&response_mode=query&scope=openid+offline_access+profile+email&state=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA& …
=> Add --reauth flag to phylum auth login

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v4.1.0
Release-Summary: Group transfer; Extension REST API access
=> Bump to v4.1.0 - Group transfer; Extension REST API access

cli/src/extension_api.ts
When adding the reference to deno_core in b1f1c81, I did not think about [this line in deno_core] which prevents loading the default libs... This flaw extends to any users of our extension_api.ts and causes issues when accessing basic things like `Deno.exit` or `Deno.args`.
To counteract that, this patch adds a lib reference to `deno.window`, which is the default library that is used for Phylum extensions.
[this line in deno_core]: https://github.com/denoland/deno/blob/98bbf87742969802b392130c536454aa61a20395/core/lib.deno_core.d.ts#L5
=> Add deno.window lib reference to extension_api.ts

Cargo.lock, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/commands/extensions/api.rs, cli/src/commands/packages.rs, cli/src/extension_api.ts, doc_templates/phylum_package.md, docs/command_line_tool/phylum_package.md
This patch modifies the `phylum package` command to use the [`/data/packages/submit`](https://api.phylum.io/api/v0/swagger/index.html#/Packages/packages_submit_endpoint) endpoint. That means that any requested package will be automatically submitted for processing if it is not already known to Phylum.
The new behavior looks like this:
```
❯ phylum package -t npm left_pad 0.0.5
⚠️  Thank you for submitting this package. Please check back later for results.
❯ phylum package -t npm left_pad 0.0.5
⚠️  Package is still processing. Please check back later for results.
```
Closes #871
=> Submit single package with `phylum package`

docs/extensions/extension_rest_api.md
Fix #897 by switching to prod for the API docs link in the extension docs.
=> Link to prod API docs

extensions/npm/README.md, extensions/poetry/README.md, extensions/yarn/README.md
Previously we were not able to run our ecosystem extensions when the user wasn't in the project's root directory, which was documented for each extension in a `Caveats` section.
Since this has been resolved and is now possible, the caveats sections have been removed.
=> Remove caveats section from ecosystem extensions

.github/workflows/test.yml, cli/src/extension_api.ts, deno.json, extensions/duplicates/main.ts, extensions/npm/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts, import_map.json
Our files have a lot of type checking issues because most of our `PhylumApi` function return `object` instead of an actual type.
Resolving these issues might mean adding lots of new types to our extension API. It might be a while before I can do that, but I am putting up the PR to keep track of it.
=> Type check TypeScript files

cli/src/api/mod.rs, cli/src/auth/server.rs, cli/src/bin/phylum.rs, cli/src/commands/auth.rs, cli/src/commands/init.rs, cli/src/commands/sandbox.rs, cli/src/format.rs, cli/src/histogram.rs, cli/src/prompt.rs, cli/src/spinner.rs, cli/src/update/unix.rs
The latest clippy nightly version further encourages inlining format arguments by warning for every instance where it is missing. This lint will likely make its way to stable in the near future and is a sensible suggestion for consistency and brevity.
=> Inline format arguments when possible

doc_templates/phylum_group_member_add.md, doc_templates/phylum_group_member_remove.md, docs/command_line_tool/phylum_group_member_add.md, docs/command_line_tool/phylum_group_member_remove.md
The example was missing the group in the command.
=> docs: Update `phylum group member add` example

cli/tests/integration.rs, cli/tests/parse.rs
Add a test which manually writes a .phylum_project file and tries to parse its lockfile to ensure there are no breaking changes in the .phylum_project format.
Closes #899.
=> Add integration test for parse without lockfile

cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/src/config.rs
This patch allows specifying multiple lockfiles and their respective
lockfile type in the `.phylum_project`, which will then be used to
submit all packages from all lockfiles when `phylum parse` or
`phylum analyze` is run.
Closes #904
=> Add multi-lockfile support to `.phylum_project`

CHANGELOG, Cargo.lock, cli/Cargo.toml
The one-line summary makes it appear that this should be a bugfix release, but there was at least one feature added to make it a minor release.
Release-Version: v4.3.0
Release-Summary: Fix sandbox executable path resolution
=> Bump to v4.3.0 - Fix sandbox executable path resolution

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/group.rs, doc_templates/phylum_group_delete.rs, docs/command_line_tool/phylum_group.md, docs/command_line_tool/phylum_group_delete.md
Add a subcommand which allows deletion of existing groups with the CLI.
Since the API's response for unknown groups is a 403 rather than a 404,
it's unfortunately not possible to provide a more descriptive error
messages when the group cannot be found without additional requests.
Closes #893.
=> Add `phylum group delete` subcommand

cli/src/app.rs, cli/src/commands/init.rs, cli/src/config.rs
Allow selecting multiple lockfiles when running `phylum init`, including
an option to specify a comma separated list of additional lockfiles.
Closes #907.
---
Depends on https://github.com/phylum-dev/cli/pull/902.
=> Add multi-lockfile support to phylum init

README.md, doc_templates/phylum_analyze.md, docs/command_line_tool/phylum_analyze.md, docs/command_line_tool/quickstart.md, docs/knowledge_base/analyzing-dependencies.md, docs/knowledge_base/groups.md
Since `phylum init` provides a better user experience than manually creating projects yourself, we should recommend it over the other alternatives.
Closes #917.
=> Switch to `phylum init` for CLI docs

lockfile/src/parsers/gem.rs, tests/fixtures/Gemfile.lock
The ruby parser expected a loose version for all dependencies and sub-dependencies. However it is not required for sub-dependencies to have any version at all.
To fix this, the loose version parser has been extended to allow for a completely empty string as an alternative to a version and the tests were modified to ensure this is tested for.
Closes #918.
=> Fix gem parser for dependencies without version

Cargo.lock, Cargo.toml, clap_markdown/Cargo.toml, clap_markdown/src/lib.rs, cli/Cargo.toml, cli/src/commands/extensions/api.rs, cli/src/commands/init.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/src/commands/project.rs, cli/src/config.rs, lockfile/src/cargo.rs, lockfile/src/parsers/gradle_dep.rs, phylum_project/Cargo.toml, phylum_project/src/lib.rs, xtask/src/main.rs
To ensure all Phylum projects using the `.phylum_project` file have a common understanding of its content, the parsing for this file has been extracted into a separate crate.
Closes #908.
=> Create separate `phylum_project` crate

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v4.4.0
Release-Summary: group delete subcommand; multi-lockfile support in init; bug fixes
=> Bump to v4.4.0 - group delete subcommand; multi-lockfile support in init; bug fixes

cli/src/commands/extensions/permissions.rs, extensions/poetry/PhylumExt.toml, extensions/poetry/main.ts
This patch updates the poetry extension to make use of the `--lock` flag for dry-running the package installation without executing any code.
Installation after analysis is done outside of the sandbox, since it seems to allow for near arbitrary code execution.
A more blacklist-based approach to deny some access (like $HOME) could likely be introduced in the future.
Closes #804.
=> Fix poetry extension

.phylum_project
This adds the `.phylum_project` file with our lockfile information to ensure the GitHub App does not run analysis on all our test fixture lockfiles.
=> Add Phylum project file

cli/src/format.rs
Since multi-lockfile is capable of running an analysis on multiple ecosystems, the existing `Ecosystem` field was no longer accurate since it only contained a single ecosystem.
Instead when multiple ecosystems are detected, they're now specified in a comma-separated list.
Closes #924.
=> Add multi-lockfile ecosystems to analysis summary

cli/src/app.rs, cli/src/commands/init.rs, cli/src/config.rs, doc_templates/phylum_analyze.md, doc_templates/phylum_parse.md, docs/command_line_tool/phylum_analyze.md, docs/command_line_tool/phylum_init.md, docs/command_line_tool/phylum_parse.md
This patch changes the `--lockfile` option in all places to allow for multiple occurrences, allowing proper multi-lockfile support for the entire CLI.
The `--lockfile-type` parameter itself is still only allowed once and applies to all other specified lockfiles. This should be fine considering it's only a last-ditch escape hatch since it should always be possible to just let the auto-parser figure things out.
Closes #906.
=> Add option to specify multiple lockfiles on CLI

extensions/poetry/main.ts
Since the `poetry install` subcommand does not have a `--lock` argument, it would cause the subcommand to fail. Since `install` should generally be based on an updated lockfile already anyway, it should be fine to run an analysis without first updating the lockfile.
However there are options allowing `install` to modify the lockfile, which is why a proper solution would likely involve parsing the `--dry-run` output instead.
=> Fix install with poetry extension

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v4.5.0
Release-Summary: Add multi-lockfile options to parse/analyze/init; fix poetry extension
=> Bump to v4.5.0 - Add multi-lockfile options to parse/analyze/init; fix poetry extension

cli/src/bin/phylum.rs, cli/src/commands/init.rs
Improve phylum init self-documentation
This changes the output of `phylum init` to be more descriptive of its
behavior, helping out inexperienced CLI users with setting up their
projects.
Closes https://github.com/phylum-dev/cli/issues/935.
---
Suggest available groups for phylum init
Previously the group input field was just a freetext field, which
created issues when the group did not exist already since groups are not
automatically created.
To resolve this, we send a request for available groups during startup
now and only allow selecting groups the user is part of.
Without any groups, the group selection process will be skipped
entirely.
The groups HTTP request is sent on startup since we have some startup
delay anyway and this way it will not harm the interactivity after this
initial …
=> Improve `phylum init` UX

lockfile/src/cargo.rs, lockfile/src/golang.rs, lockfile/src/parsers/go_sum.rs, tests/fixtures/go.sum
Previously the assumption was made that any line in the Go lockfile including `/go.mod` after its version was only included for the hash and would still have its version included without the `/go.mod` in a different line. This assumption was incorrect.
To ensure we don't ignore dependencies that are actually used, we now include all versions with and without the suffix and deduplicate that list after parsing.
This will include a lot more dependencies than what is actually used, but for security purposes over-reporting is much likely more desirable than under-reporting, considering we can't get an accurate list just by parsing the lockfile.
Closes #942.
=> Fix Go parser ignoring dependencies

CHANGELOG, Cargo.lock, cli/Cargo.toml
Release-Version: v4.6.1
Release-Summary: Fix Go parser from ignoring dependencies
=> Bump to v4.6.1 - Fix Go parser ignoring dependencies

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/jobs.rs, cli/src/format.rs, cli/src/types.rs, docs/command_line_tool/phylum_history.md
This patch fixes a long-standing issue where querying for project-specific history using `phylum history --project <PROJECT>` would return an empty list. A new `--group` flag was also added to get history for a specific group's project.
The full history endpoint does not give any group information and as such cannot be used to retrieve this information. But projects and groups have a separate endpoint providing a less detailed list of historic jobs which can be used instead.
The new history for projects includes Job ID, Label, and Creation Time.
Closes #378.
=> Fix project history endpoint

extensions/poetry/PhylumExt.toml, extensions/poetry/main.ts
This fixes some issues with the poetry ecosystem extension by switching from updating the lockfile and parsing it over to parsing the `--dry-run` flag's output instead.
The primary issue with the `--lock` flag is that the `poetry install` subcommand does not have such a flag, only `poetry add`.
Besides `poetry install`, this patch also removes any necessity to write to the project directory since `--dry-run` is immutable. This allows further lockdown of our sandbox.
Closes #931.
=> Use --dry-run output for poetry extension

.github/workflows/release.yml
This PR should not be merged until _after_ https://github.com/phylum-dev/homebrew-cli/pull/32 is merged and tested manually to work as intended.
=> ci: add release trigger to bump homebrew-cli Formula

Cargo.lock, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, docs/command_line_tool/phylum_analyze.md
Remove `--force` option from `phylum analyze` and `phylum batch`. This option was previously used to set the `is_user` value when submitting a job, but that value has no effect.
=> Remove --force option from phylum analyze

cli/src/commands/extensions/mod.rs, cli/src/deno.rs, cli/tests/common.rs, cli/tests/extensions/module_loader.rs, cli/tests/fixtures/extensions/api/main.ts, cli/tests/fixtures/extensions/module-import/fail-remote/PhylumExt.toml, cli/tests/fixtures/extensions/module-import/fail-remote/main.ts, cli/tests/fixtures/extensions/module-import/phylum-module/PhylumExt.toml, cli/tests/fixtures/extensions/module-import/phylum-module/main.ts, cli/tests/fixtures/extensions/permissions/correct-run-perms/main.ts, docs/extensions/extension_example.md, docs/extensions/extension_rest_api.md, docs/extensions/extension_sandboxing.md, extensions/duplicates/main.ts, extensions/find-permissions/main.ts, extensions/npm/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
This moves the extension API from a built-in module to a remote URI at https://phylum.io/phylum.ts, allowing non-phylum tools to resolve it automatically.
Since this introduced an additional remote dependency besides deno.land, it has also been taken as a chance to relax the import restrictions and allow for all remote URIs.
Closes #875.
Closes #864.
=> Use remote URI for extension API

cli/src/api/mod.rs, cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/tests/end_to_end/extension.rs, extensions/npm/main.ts, extensions/phylum.ts, extensions/poetry/main.ts, extensions/yarn/main.ts, import_map.json, lockfile/src/cargo.rs, lockfile/src/csharp.rs, lockfile/src/golang.rs, lockfile/src/java.rs, lockfile/src/javascript.rs, lockfile/src/lib.rs, lockfile/src/parsers/gem.rs, lockfile/src/parsers/go_sum.rs, lockfile/src/parsers/gradle_dep.rs, lockfile/src/parsers/pypi.rs, lockfile/src/parsers/yarn.rs, lockfile/src/python.rs, lockfile/src/ruby.rs
The `Parse` trait in the `lockfile` crate previously required a `package_type()` function that specified the package type for all packages returned by that parser. Going forward, we want to support lockfiles that contains multiple package types (e.g., SBOM).
This patch moves the `package_type` into the `Package` struct returned by the parser in order to support these future parsers.
=> Remove `package_type()` from `Parse` trait

cli/src/commands/extensions/api.rs, cli/src/commands/mod.rs, cli/src/commands/sandbox.rs, cli/tests/extensions/mod.rs
This provides a little improvement over the traditional "No such file or directory (os error 2)" error that is usually printed when the process specified in `PhylumApi.runSandboxed` does not exist.
Before:
```
❗ Error: No such file or directory (os error 2)
```
After:
```
Process "poetry" failed to start: No such file or directory (os error 2)
Extension error: Uncaught (in promise) Error: Process "poetry" failed to start
return Deno.core.ops.run_sandboxed(process);
^
at Function.runSandboxed (https://deno.phylum.io/phylum.ts:353:30)
at poetryCheckDryRun (file:///home/chris/programming/phylum/cli/extensions/poetry/main.ts:91:30)
at file:///home/chris/programming/phylum/cli/extensions/poetry/main.ts:79:7
```
Note that the first line in the "After" output will only be printed when STDOUT is …
=> Improve sandboxed process failure message

Cargo.lock, phylum_project/Cargo.toml, phylum_project/src/lib.rs
This PR fixes a couple issues I noticed while looking at the `phylum_project` crate.
1. `ProjectConfig::lockfiles()` returns different paths before and after the first serialization. This shouldn't be a problem for CLI because I doubt the configuration is ever used this way without first being serialized and whether or not the path starts with an extra `"./"` is not normally a problem when operating on real filesystems, so I doubt it's causing any problems today. I removed the extra `"./"`.
2. `get_current_project()` calls `find_project_conf(".", true)` and then `find_project_conf` uses `Path::parent()` to navigate to parent directories. `Path::parent()` gets the parent path, not the parent directory, because it operates only on the textual representation of the path without hitting the …
=> lockfile paths

cli/src/commands/init.rs, cli/src/commands/project.rs, phylum_project/src/lib.rs
Resolve an issue where `phylum project link <PROJECT>` would create a new config file, discarding all information stored in the `.phylum_project` file beyond the project information (i.e. lockfile data).
To ensure all auxiliary information is kept, the existing project is loaded when available and only the project-specific keys are overwritten.
Closes #994.
=> Fix `phylum project link` overwriting project file

cli/src/app.rs, cli/src/commands/packages.rs, docs/command_line_tool/phylum_package.md
Previously with the `--package-type` missing, the global configuration file's request type would be used instead. Realistically this would mean that `npm` was always used as a fallback without an ecosystem specified.
To ensure users don't get incorrect results when requesting non-npm packages, the package type option is now mandatory.
Closes #996.
=> Make `phylum package` type argument mandatory

cli/src/app.rs, cli/src/commands/jobs.rs, cli/src/config.rs
Following up on #997, this patch completely removes the request type from the global config. This also makes the `--type` parameter mandatory in the (rarely used) `phylum batch` command.
It turns out that rustfmt was ignoring a large block in `app.rs` due to the use of a raw string literal. As a part of this change, I removed the raw string literal. So you can see a significant reformatting of `app.rs`
=> Remove request type from global config

cli/src/format.rs
The format of the `phylum history` command was very hard to read and littered with unlabeled or useless information. This patch brings a new simplified format.
The new format avoids long lines, but it does so by using more lines (currently 8 lines per job). This is a necessary trade-off. I first tried a table format, but the lines were 150+ characters long.
=> Reformat `phylum history` output

cli/src/app.rs, cli/src/commands/jobs.rs
This patch adds the new `--base` option which allows passing a file
which contains a list of packages that will be ignored for analysis.
This can be used to analyze the delta between two package lists.
The expected file format is identical to the output of `phylum parse`,
so a base can be obtained using `phylum parse > base.json` and then
analyzed using `phylum analyze --base base.json`.
The option is hidden and not intended to be used by endusers, mainly to
avoid having to document the exact required file format.
Closes #1003.
=> Add base option to `phylum analyze`

cli/src/commands/extensions/api.rs, cli/tests/end_to_end/extension.rs, extensions/npm/main.ts, extensions/phylum.ts, extensions/pip/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
This exposes the functionality of adding a list of ignored package
descriptors to the extension API.
Since this is a breaking change either way, the patch also takes the
opportunity to streamline the existing APIs and use one unified package
descriptor struct for all APIs.
=> Add `ignoredPackages` parameter to extension API

cli/src/api/mod.rs, cli/src/types.rs, extensions/npm/main.ts, extensions/phylum.ts, extensions/pip/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
The API is changing to use a count of incomplete dependencies rather than a bool for completion status. This patch updates CLI to match.
=> Update PolicyEvaluationResponse to match API

extensions/pip/main.ts
The command still does not work on Linux because it uses a cross-device link, which requires a newer version of landlock to support
Ref: #990
=> Allow `phylum pip install -e .` on macOS

.github/workflows/test.yml
`ubuntu-latest` is now the same as `ubuntu-22.04`. The specific version was previously used to ensure a newer version of `shellcheck` was installed and available on the runner, so that a particular command option would be available. `ubuntu-latest`, even if it progresses, should still have at least that version of `shellcheck` installed.
Closes #467
- N/A
- N/A
=> ci: switch `ubuntu-22.04` to `ubuntu-latest`

CHANGELOG.md, cli/src/format.rs, cli/src/types.rs
The [job submission endpoint][1] does not allow null labels, but it does allow empty string. And when an empty label is submitted, it becomes a `null` label in the [project history endpoint][2].
[1]: https://api.phylum.io/api/v0/swagger/index.html#/Jobs/start_job
[2]: https://api.phylum.io/api/v0/swagger/index.html#/Projects/history_endpoint
This patch accounts for the potential `null` value in this field.
=> Handle null label in `phylum history --project`

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
Release-Version: v5.0.1
Release-Summary: Fix `phylum history --project`
=> Bump to v5.0.1 - Fix `phylum history --project`

.github/workflows/release.yml
The `name` field was not populated for the CLI v5.0.1 release, which caused `phylum update` commands from any release to fail. The `name` field is expected to be a `String` in the `GithubRelease` type and fails when there is no value (`null` instead of a `String`). The regression happened when the `generate_release_notes` option in the API call to create a release was removed in favor of specifying a `body` directly.
The documentation for this API
(https://docs.github.com/en/rest/releases/releases#create-a-release) states that:
> `generate_release_notes` boolean
> Whether to automatically generate the name and body for this release.
> If `name` is specified, the specified name will be used; otherwise, a
> name will be automatically generated. If `body` is specified, the body
> will be …
=> fix: `name` field of GitHub release not populated

extensions/npm/main.ts
Fix #1032
Arguments before the subcommand are now disallowed:
```
> phylum npm --save install sax
[phylum] This extension does not support arguments before the first subcommand.
```
=> Disallow arguments before subcommand in npm extension

.github/workflows/test.yml
This allows us to enable [merge queues][1] for this repository.
[1]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
=> Run test workflow in merge queue

cli/src/types.rs, cli/src/update/unix.rs
The `name` entry stores the GitHub Release name, which could be set to something other than the version. Using the `tag_name` entry is better since the tags are much more tightly coupled with the release version. A check of the 30 most recent CLI releases showed that the `name` and `tag_name` values were identical for every release. This means there is no worry that this change will break updates from older releases to newer ones.
=> refactor: use `tag_name` instead of `name` to identify releases

CHANGELOG.md, lockfile/src/parsers/pypi.rs, lockfile/src/python.rs, tests/fixtures/requirements-locked.txt
The `pip` "Requirements File Format" is documented here: https://pip.pypa.io/en/stable/reference/requirements-file-format/
It allows for line continuations and a host of arguments to `pip install`, which this change does not address. Instead, this change accounts for lines containing comments where the comment character (`#`) is not the first character of the line. The comment line could be indented or comments can be inline (e.g., after a valid requirement). Both types of comments were added to the test fixture.
When updating the `CHANGELOG.md`, saving the file in the IDE caused an automatic reformatting of some lines...to remove trailing whitespace and ensure consistency for the list markers (`-` everywhere instead of `*`).
Fixes #1044
=> fix: `pip` parser fails for some lines containing comments

cli/src/auth/oidc.rs
The `scopes` parameters to the token endpoint had no effect. Additionally, the `profile` and `email` scopes are unused and do not change the token that is issued.
`Content-Type: application/json` was overridden by the use of `.form()` which sets the `Content-Type` to `application/x-www-form-urlencoded`
=> Remove unnecessary OIDC parameters

docs/knowledge_base/analyzing-dependencies.md, lockfile/src/javascript.rs, lockfile/src/lib.rs
This adds support for recognizing the `npm-shrinkwrap.json` file as an alternative to the `package-lock.json`.
The file is treated like any other lockfile and if present, the `package-lock.json` will still be analyzed. This should not cause any issues and ensure all potentially used dependencies are analyzed.
Closes #1054.
=> Add npm-shrinkwrap.json support

.github/workflows/test.yml
Reverts phylum-dev/cli#1051
We have decided to hold off on using merge queues for now because GitHub does not allow control over how each PR is merged in to the queue (except on a repo-level). We use "Squash and merge" heavily in this repo and often rewrite the commit message during the merge.
_Future note: phylum-dev/cli#1051 should have also removed the `push: branches: [main]` trigger as this was causing CI to run on the same commits that `merge_queue` had already triggered. If we decide to revisit merge queues, we should disable the `push` trigger_
=> Remove `merge_group` trigger

extensions/npm/README.md, extensions/npm/main.ts
This will make use of the `npm-shrinkwrap.json` instead of the `package-lock.json` when it is available in an NPM project.
=> Use `npm-shrinkwrap.json` for npm extension

lockfile_generator/src/lib.rs
The relocator should skip files that don't exist, but was accidentally only skipping the files that do exist...
=> Fix path exists check in FileRelocator

cli/tests/extensions/permissions.rs, docs/extensions/extension_manifest.md, docs/extensions/extension_sandboxing.md, extensions/npm/main.ts, extensions/pip/main.ts, extensions/poetry/main.ts, extensions/poetry/tests.ts, extensions/yarn/main.ts
`Deno.run` is deprecated as of deno v1.33.0. This patch updates our extensions to use the preferred `Deno.Command` API
=> Use Deno.Command instead of Deno.run

cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/mod.rs, cli/src/commands/status.rs, cli/src/config.rs, cli/src/format.rs, docs/command_line_tool/phylum.md, docs/command_line_tool/phylum_status.md, phylum_project/src/lib.rs
This patch introduces a new subcommand which allows printing information
about the current project and lockfiles.
Closes #842.
Closes #982.
=> Add `phylum status` command

cli/src/commands/sandbox.rs
This patch provides a more verbose error message when creating the sandbox fails on Linux.
While it is possible that this error occurs while on Linux kernel 5.13+, this is the most likely culprit, so it is the most realistic way a user can figure out a solution by themselves.
=> Improve Birdcage errors on Linux

bump_version.sh, tag.sh
Now that we have a more detailed changelog, the one line summary is only used for the release commit and the tag message. But those aren't great places to explain a release.
=> Remove release summary

extensions/yarn/README.md
The command used in the `yarn` extension docs for usage was not correct. It specified `yarn install my-package`, which results in an error:
`Unknown Syntax Error: Extraneous positional argument ("<my-package>")`
Indeed, the docs for [yarn install](https://yarnpkg.com/cli/install) do not indicate a package to be specified on the command line. The correct command is `yarn add`, which does take a package on the command line.
=> docs: update `yarn` extension usage

extensions/yarn/main.ts, lockfile_generator/src/yarn.rs
This patch adds the `--mode=skip-build` argument to the already existing `--mode=update-lockfile` argument when generating lockfiles for yarn.
While the output is identical for both commands, adding the `skip-build` mode does speed up generation time and thus likely provides benefits even with the lockfile mode already provided.
=> Use `skip-build` mode for yarn lockfile generation

extensions/pip/main.ts
This patch ensures at least version 23.0.0 is present when trying to run the `pip` ecosystem extension.
Closes #1069.
=> Add version check to `pip` extension

lockfile_generator/src/lib.rs
This patch changes the error generated during lockfile generation when the ecosystem's package manager subprocess could not be spawned successfully.
Instead of printing the full debug formatting of the command, just the program and its argument are printed.
Closes #1084.
---
New error message example:
```
Generating lockfile for manifest "./requirements.txt" using Pip…
❗ Error: failed to spawn command "pip-compile": No such file or directory (os error 2)
```
=> Improve generator process creation error

lockfile/src/javascript.rs, tests/fixtures/package-lock.json
Some projects install packages from a top level `node_modules` folder, resulting in dependencies like this one:
```
"typescript": "file:../node_modules/typescript",
```
This was confusing our `package-lock.json` parser and causing an error such as: `Dependency 'typescript' is missing "resolved" key`
_Note_: While this patch fixes the error, this is still a filesystem dependency and will not be analyzed. Projects that use this pattern must ensure that they also submit the top-level `package-lock.json` (which contains details about where the package came from) in order to avoid missing dependencies.
=> Fix npm install from other node_modules

CHANGELOG.md
Right after merging 1dedb45, I remembered that @maxrake had mentioned [adding a CHANGELOG entry][1]... This patch adds that entry.
[1]: https://github.com/phylum-dev/cli/pull/1088#pullrequestreview-1421438826
=> Add CHANGELOG entry for external `node_modules` dependencies

cli/tests/end_to_end/extension.rs
This reverts commit e8785f76720637f08bfcc16c8d287bb0ca65a90c.
Merge this whenever staging is fixed and the test passes again
=> Revert "Temporarily disable get_package_details test (#1039)"

docs/knowledge_base/analyzing-dependencies.md
Some manifests were listed incorrectly. Some were missing. They have been updated to the current state. The language around the manifest generation was also updated to make it more clear that the tools used to perform the lockfile generation are required to be installed and available in the environment where the CLI is run. Finally, the list of lockfiles was updated to follow the same sequence as the manifest files. The output from the `phylum analyze` command on this document is still wrong but changing it now was purposefully eschewed.
=> docs: update manifest generation list and language

CHANGELOG.md, lockfile/src/spdx.rs, tests/fixtures/appbomination.spdx.json
Previously, errors would only be shown from the `tag:value parser` as each parser would be attempted if there was a failure.
This attempts to determine the type of file analyzed as a `json`, `yaml`, or `tag:value` file before deserializing to a `SpdxInfo` type allowing the errors to be correctly displayed.
Closes https://github.com/phylum-dev/cli/issues/1031
=> Display correct error messages when parsing SPDX SBOMs

cli/src/commands/parse.rs, docs/knowledge_base/analyzing-dependencies.md, docs/knowledge_base/lockfile-generation.md, lockfile_generator/src/bundler.rs, lockfile_generator/src/cargo.rs, lockfile_generator/src/go.rs, lockfile_generator/src/gradle.rs, lockfile_generator/src/lib.rs, lockfile_generator/src/maven.rs, lockfile_generator/src/npm.rs, lockfile_generator/src/pip_tools.rs, lockfile_generator/src/pipenv.rs, lockfile_generator/src/poetry.rs, lockfile_generator/src/yarn.rs
WIP to close #1095 
```
> ./target/debug/phylum parse requirements.txt     
Generating lockfile for manifest "requirements.txt" using Pip…
❗ Error: Lockfile generation failed! For details, see: https://docs.phylum.io/docs/lockfile-generation
Caused by:
0: failed to spawn command "pip-compile": Is pip-tools installed?
1: No such file or directory (os error 2)
```
=> Improve lockfile generator help output

docs/knowledge_base/lockfile-generation.md, lockfile/src/python.rs
This file will always be accompanied by a `setup.py` or `pyproject.toml`
`setuptools` [documents][1] how to use `setup.cfg` without `setup.py`, but doing that requires `pyproject.toml`. Indeed, `pip-compile` fails when it is run on a project that only has `setup.cfg`:
```
build.BuildException: Source <path> does not appear to be a Python project: no pyproject.toml or setup.py
```
[1]: https://setuptools.pypa.io/en/latest/setuptools.html#setup-cfg-only-projects
Related to #1102
=> Remove setup.cfg as a manifest

lockfile/src/spdx.rs
Add missing `#[test]` attribute on one of the SPDX unit tests.
Related to https://github.com/phylum-dev/cli/issues/1011
=> Add missing test attribute

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
Release-Version: v5.3.0
Cutting v5.3.0-rc2 today. Preparing this PR for a v5.3.0 release on Tuesday (2023-06-20)
=> Bump to v5.3.0

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/commands/jobs.rs, cli/src/format.rs, cli/src/types.rs
This patch uses the new raw policy endpoint to fix the output of the analysis command to be properly formatted for a terminal emulator rather than just printing the default markdown.
Closes #1116.
=> Fix analysis report output

lockfile/src/parsers/mod.rs, lockfile/src/parsers/pypi.rs, lockfile/src/python.rs, tests/fixtures/requirements-locked.txt
This fixes the handling of line continuations in the requirements.txt file.
It also resolves an issue where the `--hash` argument was not accepted by the lockfile parser and caused the parsing of the file to fail.
Closes #1117.
=> Fix line continuations and --hash in python parser

lockfile/src/parsers/gem.rs, lockfile/src/parsers/go_sum.rs, lockfile/src/parsers/gradle_dep.rs, lockfile/src/parsers/mod.rs, lockfile/src/parsers/pypi.rs, lockfile/src/parsers/spdx.rs, lockfile/src/parsers/yarn.rs
Calling this type `Result` leads to confusion because it has two generic parameters just like `std::result::Result`. But the parameters are for input and output, not ok and error.
Using `IResult` is less confusing.
=> Rename parsers::Result to parsers::IResult

CHANGELOG.md, lockfile_generator/src/lib.rs, lockfile_generator/src/yarn.rs
Since yarn v1 isn't able to generate a lockfile without installing the dependencies and executing their build code, it could be dangerous to automatically generate lockfiles for the user.
To fix this issue, the lockfile generator will now return an error when lockfile generation is attempted with the yarn generator and only version 1 is used by the project.
While the lockfile generation with yarn v1 still worked and it would provide protection against vulnerable code in the target executable, it is safer to leave the lockfile generation up to the user so they're in full control.
Closes #1086.
=> Disable lockfile generation for yarn v1

CHANGELOG.md, extensions/npm/main.ts, extensions/pip/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
This fixes an issue where ecosystem extension invocations wouldn't work unless they also had a subcommand specified. This specifically prevented the common `--help` flag from being used on its own.
Closes #1025.
---
I think this is a way simpler and more reliable way to prevent options before subcommands, however it still isn't a bulletproof design. In this scenario something like `yarn add install` would fail for example, but I don't think any of the package manager subcommands have packages with the same name that are popular enough to make this an issue.
The other alternative would be a more complicated argument parser that actually checks for at least `-` at the start of arguments, which might require some edgecase handling too, but I'd like to avoid that unless necessary. If we did …
=> Fix ecosystem extensions without subcommand

CHANGELOG.md, docs/command_line_tool/phylum_analyze.md, docs/command_line_tool/phylum_init.md, docs/command_line_tool/phylum_parse.md, docs/knowledge_base/analyzing-dependencies.md, docs/knowledge_base/lockfile-generation.md, lockfile/src/javascript.rs, lockfile/src/lib.rs, lockfile_generator/src/lib.rs, lockfile_generator/src/pnpm.rs, tests/fixtures/pnpm-lock.yaml
This adds support for the new `pnpm-lock.yaml` lockfile type and its
package manager `pnpm`. Supported are both parsing the lockfile itself
and generating a lockfile from the `package.json`.
Closes https://github.com/phylum-dev/cli/issues/1138.
=> Add support for pnpm

extensions/CHANGELOG.md, extensions/phylum.ts
The code was failing `deno check` because the type system was confused about the type of `fetchInit.headers`. This patch removes the confusion.
This patch also fixes the conditional around the `Content-Type` header, which was wrong.
=> Split header initialization into separate function

Cargo.lock, cli/Cargo.toml, cli/src/deno.rs
This patch updates the `deno` crates to latest. Only one change to account for, which was the removal of `.force_op_registration()`. This update happened in `deno` commit [`34dac6c`](https://github.com/denoland/deno/commit/34dac6c6efa75f38c29031a65db1ee3332a67259) because the function is no longer required.
This should fix the issues seen in #1144
=> Bump deno versions

.github/workflows/test.yml
Our builds are too large for GitHub's Windows runners and they keep running out of disk space. And since we don't officially support native Windows, it's time for these builds to go.
After all, 2023 is the Year of the Linux Desktop.
=> Remove Windows CI

CHANGELOG.md, docs/command_line_tool/phylum_analyze.md, docs/command_line_tool/phylum_init.md, docs/command_line_tool/phylum_parse.md, docs/knowledge_base/analyzing-dependencies.md, lockfile/src/csharp.rs, lockfile/src/lib.rs, tests/fixtures/packages.lock.json
This patch adds the ability for CLI to parse NuGet's `packages.lock.json` lockfiles.
Currently this only supports the format itself and does no generation from `*.csproj` files to `packages.lock.json` using `nuget`.
Closes #1056.
=> Add support for NuGet lockfiles

.github/workflows/test.yml, cli/tests/extensions/permissions.rs
The `extensions::permissions::correct_net_permission_successful_install_and_run` test started failing after the main Phylum website was updated. It no longer contains the lowercase text `<!doctype html>` and now it is uppercase: `<!DOCTYPE html>`.
A workaround is also added to the `Test` workflow, to free up disk space. Without it, the linking step causes an error due to running out of disk space.
Fixes #1157
=> test: update test for phylum website change

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
CLI v5.4.0 was rejected before release due to a race condition in deno. The race condition was fixed in #1149 and now we can release CLI v5.5.0.
The `v5.4.0` tag will remain, but mention of the release has been removed from the Changelogs so that they reflect our actual releases.
Release-Version: v5.5.0
=> Bump to v5.5.0

Cargo.lock, cli/Cargo.toml, cli/src/spinner.rs
See the related [GitHub security advisory](https://github.com/advisories/GHSA-g98v-hv3f-hcfr). This patch removes our dependency on `atty`, because it is unmaintained.
Alternately, I could have used the [`is-terminal`](https://crates.io/crates/is-terminal) crate and avoided the MSRV bump. But rust 1.70.0 is already available in [Homebrew](https://formulae.brew.sh/formula/rust#default), which is the only package manager that we currently target. So there is no real need to support anything older.
=> Use std::io::IsTerminal instead of atty

cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/commands/extensions/api.rs, extensions/CHANGELOG.md, extensions/npm/main.ts, extensions/phylum.ts, extensions/pip/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
This adds the new `getJobStatusRaw` and `checkPackagesRaw` extension APIs which allow retrieving a more detailed analysis report.
The ecosystem extensions are also switched over to `checkPackagesRaw`, allowing the output to match the CLI's analysis output, which provides additional details on failure.
Closes #1093.
=> Add failure reason for ecosystem extensions

.github/workflows/test.yml
When splitting the workflows in c26ac6b, the all features test workflow was left without a step to setup the Rust toolchain. This has led to failures as the wrong toolchain can get used in some situations (particularly on the self-hosted runner).
=> Add toolchain setup to all features test

CHANGELOG.md, cli/src/commands/parse.rs
The current search could potentially miss lock files in the current path.
This changes to search the current path first before sub directories.
Either way I imagine could still choose an incorrect lockfile related to another ecosystem if present.
Closes https://github.com/phylum-dev/cli/issues/1170
=> fix: update lockfile detection to search root directory first

Cargo.lock, cli/Cargo.toml, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/auth/mod.rs, cli/src/auth/oidc.rs, cli/src/auth/server.rs, cli/src/commands/auth.rs, cli/src/commands/extensions/api.rs, cli/src/test.rs, docs/command_line_tool/phylum_auth_login.md, docs/command_line_tool/phylum_auth_register.md
This patch updates CLI to generate and use Locksmith tokens (aka "API keys")
For backwards compatibility, OIDC refresh tokens are still supported in the `settings.yaml` or via the `PHYLUM_API_KEY` environment variable. But they are no longer generated.
=> Use locksmith tokens

CHANGELOG.md, cli/src/commands/parse.rs
Previously when a manifest was specified as the target for an analyze or
parse operation, the directory would be walked downwards depth-first to
find a lockfile for this manifest. This would both prefer lockfiles
farther away from the manifest and allow lockfiles from subdirectories.
This patch reverses the search direction for lockfiles, since they're
generally at or above their corresponding manifest. The new logic
prefers lockfiles closest to the manifest and searches the directory
tree upwards from there.
Closes https://github.com/phylum-dev/cli/issues/1170.
=> Reverse search direction for manifests' lockfiles

CHANGELOG.md, cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/tests/parse.rs
The lockfile paths were being submitted with an absolute path if the project root was set.
This can be caused by using relative lockfile paths in in the `.phylum_project`.
Closes https://github.com/phylum-dev/cli/issues/1169
=> Use relative paths when project root is set

CHANGELOG.md, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/auth.rs, cli/src/format.rs, cli/src/test.rs, cli/src/types.rs, docs/command_line_tool/phylum_auth.md, docs/command_line_tool/phylum_auth_list-tokens.md
This patch adds a new `list-tokens` subcommand to the existing `auth` subcommand which lists all locksmith tokens associated with the logged in user.
See #1176.
=> Add `auth list-tokens` subcommand

CHANGELOG.md, clap_markdown/src/lib.rs, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/auth/server.rs, cli/src/bin/phylum.rs, cli/src/commands/auth.rs, cli/src/commands/group.rs, cli/src/commands/jobs.rs, cli/src/commands/packages.rs, cli/src/commands/parse.rs, cli/src/commands/project.rs, cli/src/format.rs, cli/src/types.rs, doc_templates/phylum_auth_revoke-token.md, doc_templates/phylum_auth_set-token.md, docs/command_line_tool/phylum_auth.md, docs/command_line_tool/phylum_auth_login.md, docs/command_line_tool/phylum_auth_register.md, docs/command_line_tool/phylum_auth_revoke-token.md, docs/command_line_tool/phylum_auth_set-token.md
This adds a new subcommand to the `auth` subcommand which allows
revoking Locksmith API tokens.
It is possible to either specify one or more tokens as CLI arguments, or
alternatively interactively select which tokens should be revoked.
Closes https://github.com/phylum-dev/cli/issues/1176.
---
Small Disclaimer: I might have gone a little overboard with the implementation of this issue, however I do believe that the ease of use provided by the selection UI justifies the small additional code complexity.
=> Add `phylum auth revoke-token` subcommand

CHANGELOG.md, lockfile/src/parsers/gem.rs, lockfile/src/ruby.rs, tests/fixtures/Gemfile.empty.lock
This fixes an issue where the bundle lockfile parser would fail when encountering the lockfile generated by `bundle init; bundle lock`.
Closes #1183.
=> Fix `Gemfile.lock` parsing with zero dependencies

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/deno.rs
This fixes an issue with extensions where the reported line for an error did not match the supplied code, since the error was based on the transpiled JavaScript.
To make sure the error can be mapped from JavaScript back to the original TypeScript, a transpiler cache has been introduced which is used to retrieve the original source map when an error is encountered.
Fixes #961.
=> Fix reported lines in extension errors

.github/workflows/release.yml, CHANGELOG.md, extensions/bundle/PhylumExt.toml, extensions/bundle/README.md, extensions/bundle/main.ts
=> Add bundler ecosystem extension

CHANGELOG.md, extensions/npm/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
Almost all ecosystem package managers will install all missing packages when removing even unrelated packages. As a result it is required that we run an analysis even during package removal.
Closes #1189.
=> Ensure ecosystem extensions check removal

CHANGELOG.md, xtask/Cargo.toml
Fix #965 by adding a `selfmanage` feature to `xtask`. This allows generating completion files with or without the `selfmanage` commands.
```
cargo run -p xtask -- gencomp
```
```
cargo run -p xtask --no-default-features -- gencomp
```
=> Add selfmanage feature to xtask

cli/src/commands/parse.rs
As shown in #1177, some lockfile parsing errors result in poor error messages because the lockfile path is not always known.
This patch adds the lockfile path as context on the error to ensure that it will be present in the error message.
**Before**
```
> phylum parse
❗ Error: Is a directory (os error 21)
```
**After**
```
> phylum parse
❗ Error: could not parse lockfile: ./Cargo.lock
Caused by:
Is a directory (os error 21)
```
=> Improve lockfile parsing errors

cli/src/commands/extensions/extension.rs, cli/src/commands/uninstall.rs, cli/src/deno.rs, cli/src/dirs.rs, cli/tests/common.rs, cli/tests/extensions/mod.rs, cli/tests/extensions/module_loader.rs, cli/tests/fixtures/extensions/run-count/PhylumExt.toml, cli/tests/fixtures/extensions/run-count/main.ts, extensions/CHANGELOG.md
This patch allows extensions to use `localStorage` to store state. Each extension has separate state and it is removed when the extension is uninstalled. Additionally, only installed extensions are allowed to persist state.
_Note:_ This also enables usage of `sessionStorage`, but the session lasts only as long as the process, so this does not provide any additional value.
=> Enable Web Storage API for extensions

lockfile/src/cyclonedx.rs, lockfile/src/spdx.rs
Correctly identifies SPDX SBOM files and also identifies CycloneDX SBOMs in the form of `<proj_name>.bom.json`
Closes https://github.com/phylum-dev/cli/issues/1212
=> Update SBOM identification

cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/tests/end_to_end/extension.rs, docs/extensions/extension_example.md, extensions/CHANGELOG.md, extensions/phylum.ts
This patch changes the output of the `PhylumApi.parseLockfile` method to add the relative path to the origin lockfile to each individual package.
This allows for the UI to display the lockfile path without extensions themselves having to remap the array of packages themselves.
Closes #1219.
=> Add relative path to each package in parseLockfile

CHANGELOG.md, cli/src/format.rs
Packages with all rejections suppressed should not be displayed in the output report. This patch corrects the filter to account for that.
=> Don't print package with no active rejections

Cargo.lock, cli/Cargo.toml, cli/tests/sandbox.rs
This fixes a regression introduced in 041be47 which would prevent local sockets from working when the network sandbox was enabled.
=> Bump Birdcage to v0.3.1

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, lockfile_generator/Cargo.toml, lockfile_generator/src/bundler.rs, lockfile_generator/src/cargo.rs, lockfile_generator/src/dotnet.rs, lockfile_generator/src/go.rs, lockfile_generator/src/gradle.rs, lockfile_generator/src/lib.rs, lockfile_generator/src/maven.rs, lockfile_generator/src/npm.rs, lockfile_generator/src/pip.rs, lockfile_generator/src/pipenv.rs, lockfile_generator/src/pnpm.rs, lockfile_generator/src/poetry.rs, lockfile_generator/src/yarn.rs
When generating a lockfile for a Cargo manifest, it is possible that the lockfile will be placed in a parent directory rather than the manifest's directory. Since this wasn't accounted for, lockfile generation would fail and the lockfile would not get cleaned up.
To allow tracking lockfiles generated in directories above the manifest, the `find_workspace_root` function of cargo is used now to locate the place where the lockfile will be put.
---
One thing to note is that this probably also applies to other ecosystems, but I wanted to focus on Cargo for now since I'm most confident this will actually work.
=> Fix cargo lockfile generation

cli/src/commands/extensions/permissions.rs, extensions/CHANGELOG.md
This patch fixes a regression from e166fce that was causing `net = true` permissions to be handled like `net = false`. This meant than an extension using `net = true` would only be able to access the Phylum API domains from their extension code. Subprocesses and the network sandbox were unaffected by this regression.
=> Fix allow all networking permissions

.github/workflows/cargo-update.yml
This patch addresses many little issues:
- The backtick (\`) character was being interpreted as shell expansion in the `git commit` command
- The `noreply` email for `phylum-bot` did not include the user ID
- This repository does not use Conventional Commits, so the `build:` prefix was unnecessary
=> Fix issues with cargo-update workflow

CHANGELOG.md, Cargo.lock, lockfile_generator/Cargo.toml, lockfile_generator/src/lib.rs, lockfile_generator/src/npm.rs, lockfile_generator/src/pnpm.rs, lockfile_generator/src/yarn.rs
This patch fixes the lockfile generation for workspaces with npm, yarn, and pnpm.
See #1236.
=> Fix JavaScript workspace lockfile generation

CHANGELOG.md, lockfile/src/golang.rs
While lockfile generation was already implemented, it was never actually enabled in the `lockfile` crate. This patch enables the Go generator, which has been tested both with workspaces and normal go projects.
=> Fix go lockfile generation

CHANGELOG.md, lockfile/src/lib.rs
This fixes an issue where manifests would get filtered out with a lockfile of a different ecosystem being present in a parent directory.
Closes #1245.
=> Fix manifest filtering for different ecosystems

cli/src/app.rs, docs/commands/phylum_analyze.md, docs/commands/phylum_group_create.md, docs/commands/phylum_group_delete.md, docs/commands/phylum_history.md, docs/commands/phylum_init.md, docs/commands/phylum_package.md, docs/commands/phylum_parse.md, docs/commands/phylum_project_create.md, docs/commands/phylum_project_delete.md, docs/commands/phylum_project_link.md, docs/commands/phylum_project_list.md
Previously the case for the value names of CLI arguments was mixed lower and upper case. Since the standard on unix systems is usually uppercase, all options have been changed to comply with this format.
=> Unify clap `value_name` case

Cargo.lock, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/extensions/api.rs, cli/src/commands/init.rs, cli/src/commands/project.rs, cli/src/format.rs, cli/tests/common.rs, docs/commands/phylum_init.md, docs/commands/phylum_project.md, docs/commands/phylum_project_create.md, docs/commands/phylum_project_status.md, docs/commands/phylum_project_update.md, extensions/phylum.ts
This patch adds the new `repository_url` field to all subcommands
creating new projects. This includes `phylum init`, `phylum project
create`, and the `create_project` extension API.
See https://github.com/phylum-dev/roadmap/issues/361.
=> Add repository URL to project

CHANGELOG.md, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/find_lockable_files.rs, cli/src/commands/mod.rs, lockfile/src/lib.rs
This patch adds a new subcommand which allows looking up all lockfiles
and manifests in the current directory without performing any filtering
on the result.
The manifest resolution is also changed to remove manifests when there
is a manifest of the same ecosystem in a directory above, indicating
that the project is likely a workspace.
Closes https://github.com/phylum-dev/cli/issues/1255.
=> Add find-lockable-files subcommand

CHANGELOG.md
This fixes the inconsistent newlines after changelog headings between the main and the extension changelog.
=> Unify changelog formatting

CHANGELOG.md, docs/lockfile_generation.md, lockfile/src/java.rs
This fixes an issue where build.gradle files written in Kotlin wouldn't be detected as manifests.
=> Add support for build.gradle.kts manifests

CHANGELOG.md, lockfile_generator/src/pnpm.rs
This fixes an issue where the pnpm lockfile generator would fall back to `./pnpm-lock.yaml` if no workspace was present, instead of the correct `<MANIFEST_PATH>/../pnpm-lock.yaml`.
=> Fix pnpm lockfile generation

CHANGELOG.md, lockfile/src/cyclonedx.rs
The BOM parser should ignore and warn when encountering packages with unsupported ecosystems.
closes https://github.com/phylum-dev/cli/issues/1278
=> Fix parsing BOM packages with unsupported ecosystems

CHANGELOG.md
The entries from #1269 and #1270 were accidentally put in the wrong section. The patch fixes that.
It looks like #1269 was based on an old `main`, so the entry ended up in the wrong spot when merged. And since #1270 was done on the same day, it was natural to put that changelog entry right next to the other one.
=> Move CHANGELOG entries to correct section

Cargo.lock, cli/src/app.rs, cli/src/commands/extensions/api.rs, cli/src/commands/extensions/permissions.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, docs/commands/phylum_analyze.md, docs/commands/phylum_parse.md, extensions/phylum.ts, lockfile/src/lib.rs
This patch uses Birdcage to run lockfile generation in a restricted environment to prevent malicious actors from executing code using Phylum's lockfile generation.
=> Add sandbox for lockfile generation

CHANGELOG.md, lockfile/src/javascript.rs, lockfile/src/lib.rs, tests/fixtures/package-lock.json
=> Fix package-lock.json deps with aliased names

CHANGELOG.md, cli/src/app.rs, cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, docs/commands/phylum_analyze.md, docs/commands/phylum_parse.md, docs/lockfile_generation.md, extensions/CHANGELOG.md, extensions/phylum.ts
=> Add option to disable lockfile generation

Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md, extensions/find-permissions/main.ts
This fixes an issue where dependencies on symlinked directories or files would report overly coarse results.
=> Fix `find-permissions` for symlinks

cli/src/commands/extensions/api.rs, extensions/CHANGELOG.md, extensions/phylum.ts
Currently the lockfile generation sandbox does not spawn a separate process, thus enabling the sandbox for the calling process directly. Since extensions might be doing other things after generating the lockfile for a manifest, this could prevent them from operating correctly.
This patch removes the sandboxing for lockfile generation when calling `parseLockfile` from an extension. In the future it should be possible to enable this again by spawning a separate process for lockfile generation.
=> Disable sandbox for extension lockfile generation

CHANGELOG.md, cli/src/app.rs, cli/src/commands/project.rs, docs/commands/phylum_project_status.md
=> Add project args to `phylum project status`

cli/src/commands/parse.rs
This changes the error output for lockifests which cannot be parsed as lockfiles when manifest generation is disabled with `--no-generation`. Instead of printing the parsing error of the lockfile, we now print an error that manifest generation is required.
Closes #1295.
=> Fix generation error for invalid lockifests

cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/extensions/api.rs, cli/src/commands/generate_lockfile.rs, cli/src/commands/mod.rs, cli/src/commands/parse.rs, extensions/CHANGELOG.md, extensions/phylum.ts
Before this patch lockfile generation would always happen in the CLI's process, which inevitably applied the sandbox to the process itself making the execution environment after generation severely limited.
To allow for the CLI and extensions to use sandboxed lockfile generation without having to spawn a separate process, the generation itself is now always executed in a separate process if sandboxing is requested.
Closes #1296.
=> Add subprocess for sandboxed lockfile generation

.github/workflows/release.yml, .github/workflows/test.yml, Cargo.lock, cli/Cargo.toml, cli/src/commands/extensions/api.rs, cli/src/deno.rs
This includes migration to the new `op2` macro because `op` is now deprecated (See denoland/deno_core#279). The new macro requires explicit annotation for string and serde parameters and return values because of the performance hit. We use these heavily (and don't care about the performance).
=> Bump deno version

.github/workflows/release.yml
The [release workflow](https://github.com/phylum-dev/cli/actions/workflows/release.yml) was broken...since [the Deno version bump](https://github.com/phylum-dev/cli/commit/ae113fad36aefec040689b885468005be0e8f2e6). This PR fixes the two failing jobs. Don't mind all the WIP commits...it worked first try...after some help from @kylewillmon !
=> Fix broken release workflow

cli/src/commands/parse.rs
Fix #1316 
This patch causes `phylum parse` to use the same format that is currently used by API. This means using the `lockfile` key just like CLI v5.9.0 rather than a more broad `origin` key.
```
> phylum parse ./requirements.txt
Generating lockfile for manifest "requirements.txt" using Pip…
[
{
"name": "PyYAML",
"version": "6.0.1",
"type": "pypi",
"lockfile": "requirements.txt"
}
]                                                                                                                                                                                                                                                                                                                               
```
=> Restore lockfile in phylum parse output

cli/src/commands/generate_lockfile.rs
Gradle [install instructions][1] list extracting to `/opt/gradle` as one method of installing the tool. This patch should make those installs function correctly.
[1]: https://gradle.org/install/
=> Allow /opt/gradle for Lockfile generation

CHANGELOG.md, Cargo.lock, cli/Cargo.toml
Release the fix for `/opt/gradle` installations
Release-Version: v6.0.1
=> Bump to v6.0.1

.github/workflows/release.yml
This change goes with the one in https://github.com/phylum-dev/documentation/pull/80 and should not be merged until after that PR, in case there are changes there that need to be reflected here.
=> ci: add documentation update trigger to release workflow

cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/auth.rs, cli/src/commands/parse.rs, cli/src/config.rs, docs/commands/phylum.md
This patch removes all output from `parse-sandboxed` that isn't directly related to its purpose of parsing dependency files. This includes omitting both config and update messages.
Closes #1328.
=> Remove unrelated output from `parse-sandboxed`

cli/src/api/mod.rs, cli/src/commands/extensions/api.rs, cli/src/commands/jobs.rs, cli/src/commands/parse.rs, cli/src/types.rs, extensions/CHANGELOG.md, extensions/phylum.ts, lockfile/src/parse_depfile.rs
This patch changes the `api::submit_request` function to accept PURLs with optional dependency file in addition to the existing package descriptors.
Closes #1336.
=> Accept PURLs for package submission

CHANGELOG.md, cli/src/commands/parse.rs, extensions/pip/PhylumExt.toml, extensions/pip/main.ts
This fixes lockfile generation with pip when it is installed in `~/.local/lib/python*/site-packages/pip`.
It also fixes an issue where `pyenv` installed through the package manager wouldn't allow for lockfile generation.
Closes #1349.
=> Fix sandbox exceptions for local pip installs

docs/quickstart.md
There is now official support from Homebrew for the Phylum CLI. That means it can be installed for macOS users alongside their other homebrew applications as simply as `brew install phylum-cli`. This PR reflects that new option as the preferred one.
=> docs: update macOS CLI install command

docs/lockfile_generation.md
This documents the behavior of the sandbox in connection to automatic lockfile generation when running `analyze`/`parse` on manifest files.
See #1350.
=> Add docs for lockfile generation sandbox

.github/workflows/release.yml, README.md, docs/quickstart.md
The trigger is no longer needed now that:
* The `phylum-cli` formula is included in `homebrew-core`
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/p/phylum-cli.rb
* The `phylum-cli` formula is included in the `autobump` workflow
* https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/autobump.yml
* https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt#L1011
* This workflow runs once every three hours
* It will automatically create new update PRs for outdated formula
Some documentation updates were made to be more consistent in wording.
- See https://github.com/phylum-dev/roadmap/issues/409
- N/A 
- N/A
=> ci: remove trigger for `homebrew-cli` formula bump

CHANGELOG.md, Cargo.lock, cli/Cargo.toml
- Improved sandboxing error message for unsupported kernel versions
=> Bump to v6.1.2

README.md, docs/quickstart.md
This change reverts "the Phylum CLI" language to simply "phylum" when discussing the install instructions. Some more discussion can be found in #1362, where the change was initially made.
Also, the Homebrew formula for `phylum-cli` has an alias to `phylum` now so changing the install instructions to `brew install phylum` is simpler and more intuitive for users.
=> docs: use "phylum" to refer to CLI and formula for install

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
- Crashes when parsing invalid lockfiles
- `phylum group transfer` subcommand
- Owner email from `phylum group list` results
=> Bump to v6.2.0

extensions/phylum.ts
This PR changes the `PhylumApi.fetch` method to only set the `Content-Type` header when it is sending content. Most API endpoints either expect a JSON request body with `Content-Type: application/json`, or expect no content (and don't care about `Content-Type` at all). There are a couple API endpoints that optionally accept a request body which may or may not be JSON, and for those endpoints the `Content-Type` header must be set to JSON if and only if the request body is JSON. A null body is not JSON, so sending a request to one of those endpoints using the usual `PhylumApi.fetch("v0", "/endpoint", { method: "POST" })` results in a 400 error when the server tries to decode a 0-byte body as JSON.
This PR doesn't attempt to do any sort of autodetection to determine if a request body is …
=> Only set content-type header with content

CHANGELOG.md, lockfile/src/parsers/spdx.rs, lockfile/src/spdx.rs
In SPDX documents, it's possible to have a self-descriptive structure where the document describes itself as a package. This change uses the package relationships to remove that package from the list. Also fixed an issue where parsing certain text files with additional package info causes the parsing to fail.
Closes https://github.com/phylum-dev/cli/issues/1381
Cloess https://github.com/phylum-dev/cli/issues/1382
=> Use `SPDX` package relationships to filter out the project added a dependency

CHANGELOG.md, lockfile/src/parsers/spdx.rs, lockfile/src/spdx.rs
This uses the download location to match with known package registries for packages without an external ref.
Closes https://github.com/phylum-dev/cli/issues/1384
=> Use `SPDX` download location to determine package registry

Cargo.lock, cli/src/api/mod.rs, cli/src/types.rs, extensions/phylum.ts
These changes are not in API yet (not until I update `phylum-types`, as I did here), but we can pre-empt them here in CLI.
The only affected type from `phylum-types` that we were using here seems to be `JobDescriptor` (through `AllJobsStatusResponse`). There was a test fixture related to that type that needed to be updated (also, we previously were not returning `action` in that response, so I went ahead and removed that too).
We are using our own local `Package` type here as we begin to transition from `phylum-types`, so I had to remove `issue_impacts` locally, too.
ref https://github.com/phylum-dev/roadmap/issues/400
=> Accomodate API endpoint response cleanup.

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
- Improve parsing of non-UTF-8 encoded pom.xml files
- `SPDX` SBOM registry determination from downloadLocation
- `SPDX` parsing adding the described package as a dependency
- `SPDX` parsing certain text files with optional package fields
=> Bump to v6.3.0

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/commands/parse.rs, cli/src/commands/sandbox.rs
Subprocesses spawned inside a sandbox for extensions or lockfile generation would keep running when the CLI is killed, since signals were not propagated to the child process.
This patch updates CLI to use Birdcage 0.8.0 which spawns a separate init process for PID 1 inside the PID namespace automatically terminating any child even if unresponsive.
Closes #1370.
=> Fix termination of sandboxed processes

CHANGELOG.md, cli/src/deno.rs, lockfile/src/golang.rs, lockfile/src/parse_depfile.rs, lockfile/src/parsers/go_sum.rs
Updates the `go.sum` parser to filter out modules with `<version>/go.mod`. These modules aren't not used to build the package but used to perform [minimal version selection](https://go.dev/ref/mod#minimal-version-selection).
Part of https://github.com/phylum-dev/cli/issues/1396
=> Improve `go.sum` parser

CHANGELOG.md
This entry was mistakenly put in the wrong section. 760cefd was not included in the last release.
=> Move CHANGELOG entry for process cleanup

CHANGELOG.md, lockfile/src/lib.rs, lockfile/src/parse_depfile.rs, lockfile/src/parsers/pypi.rs, lockfile/src/python.rs, tests/fixtures/requirements-locked.txt, tests/fixtures/requirements-unlocked.txt
=> Add support for PyPI local versions

lockfile/src/lib.rs
Updates the lockfile detection to ignore go.mod files and default to the go.sum parser.
If the go.sum is missing, the go.mod file is recognized and can be parsed if the go directive is >= 1.17.
If the go directive criteria is not satisfied, the user will receive a message that the lockfile generation is required.
```bash
❯ phylum analyze -p test
❗ Could not parse manifest: Parsing "go.mod" requires lockfile generation, but it was disabled
```
Closes https://github.com/phylum-dev/cli/issues/1421
=> Use the `go.sum` parser as the default lockfile format for golang

CHANGELOG.md, lockfile_generator/src/cargo.rs, lockfile_generator/src/lib.rs, lockfile_generator/src/pip.rs, lockfile_generator/src/yarn.rs
Previously only the STDERR was printed whenever lockfile generation encountered a non-zero exit code from the package manager, however some package managers like `dotnet` print their errors to STDOUT.
This patch reworks the output in these error cases to print both STDERR and STDOUT and formats things a little nicer to make it easy to keep the two apart.
Closes #1425.
=> Add STDOUT to lockfile generation error message

CHANGELOG.md, cli/src/commands/parse.rs
Maven has a `libexec` folder that contains scripts that get executed when generating lockfiles. This patch allows execute so that those scripts are not blocked.
=> Allow execute for maven for lockfile generation

CHANGELOG.md, cli/src/commands/parse.rs
When Maven is installed on Debian-based systems via `apt`, it gets installed in `/usr/share/maven`, which is not included in the current sandbox exceptions. This patch allows execute so that it will work... hopefully.
If it still doesn't, there is a procedure for determining the complete set of exceptions needed...
I was holding off on submitting this PR because I wanted to use the `find-permissions` extension in the `phylumio/phylum-ci` Docker image first...to confirm there aren't any other exceptions needed for an `apt install maven` environment. I couldn't get it to work since Docker blocks access to the `/` root directory for mounting.
The best scenario is having the user run the extension for us, **in their environment**. The general documentation on this process [is …
=> Allow execution for apt-installed `maven`

cli/src/commands/parse.rs
Follow-up to c198a44c6ad0ef84a2167352799216cf71aa8015.
=> Add missing /etc/maven sandbox exception

extensions/find-permissions/main.ts
This patch adds two minor changes that should make the `find-permissions` extensions easier to use for people unfamiliar with it.
To ensure we don't incorrectly log that `/` is required when the command always fails, the extension now does an explicit check on `/` and outputs a detailed error on the issue.
While I wasn't able to reproduce this issue myself, there have been some reports on failures due to permission errors. To avoid the possibility of that we now explicitly handle `Deno.readDir` failures and just assume the corresponding directory is wholly required.
To improve consistency, all `console.error` calls have been changed to use red color.
=> Improve robustness of find-permissions extensions

CHANGELOG.md, lockfile_generator/src/maven.rs
This patch silences the maven lockfile generator to avoid part of this output ending up in the target effective-pom.xml.
=> Remove extraneous output from maven generator

cli/src/commands/parse.rs
This fixes several severe issues with c198a44, which was incorrectly matching whole path segments.
=> Fix OpenJDK path detection

CHANGELOG.md, cli/src/commands/parse.rs, lockfile_generator/Cargo.toml, lockfile_generator/src/gradle.rs
This patch adds a temporary init script using Gradle's `--init-script` CLI parameter to force enable lockfile writing during lockfile generation.
=> Add init script for gradle lockfile generation

CHANGELOG.md, docs/lockfile_generation.md, docs/supported_lockfiles.md, lockfile/src/java.rs, lockfile/src/lib.rs
This patch accepts Gradle lockfiles inside the `gradle/dependency-locks` directory, which all share Gradle's `.lockfile` suffix but have various different file names.
Closes #1459.
=> Add support for older Gradle lockfiles

CHANGELOG.md, lockfile/src/lib.rs
This fixes an issue where Gradle 5 lockfiles would not override manifest files in the same directory since the lockfiles themselves are stored in a subdirectory.
=> Fix Gradle 5 lockfiles not overriding manifests

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, docs/lockfile_generation.md, extensions/CHANGELOG.md, lockfile/src/lib.rs
Some language changes were made to the `CHANGELOG` and comments,
to be more precise about the affected Gradle versions and how the
dependency file detection logic works.
Release-Version: v6.6.4
=> Bump to v6.6.4

.github/workflows/release.yml, .github/workflows/test.yml
The GitHub-hosted macOS runners have been updated to include arm64 M1 options now. This PR switches our workflows to use them instead of the self-hosted runner. There is more availability for these runners and they run just about as fast, if not faster when accounting for parallel jobs. The `release` workflow was updated to change `macos-latest` to `macos-14` to be specific about the version in the matrix and allow for adding additional versions in the future.
Resources:
* [Standard GitHub-hosted runners for public repos](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
* [Latest `macos-14` image release](https://github.com/actions/runner-images/releases/tag/macos-1 …
=> ci: use GitHub-hosted macOS runners

CHANGELOG.md, lockfile/src/javascript.rs, tests/fixtures/package-lock.json
This fixes an issue where the lockfile parser for JavaScript's `package-lock.json` was too restrictive and would fail parsing valid lockfiles.
As a solution all packages without explicit `resolved` field are now ignored, since these are the only packages we're capable of analyzing anyway.
=> Fix package-lock.json lockfile parsing failures

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/commands/init.rs
Closes #1465.
---
This uses the `git2` crate, which is pretty big. But I think it's the most sensible implementation for this feature.
=> Infer repository URL from git info

CHANGELOG.md, lockfile/src/csharp.rs, tests/fixtures/sample.csproj
This fixes an issue where the `.csproj` parser would ignore uppercase
version fields on `PackageReference`.
=> Fix msbuild parsing with lowercase version field

cli/src/types.rs
This updates the response of the `phylum group list --json` command to include all the latest fields of the corresponding API endpoint.
=> Update `UserGroup` API type

.github/workflows/test.yml, Cargo.lock, cli/Cargo.toml, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/parse.rs, lockfile_generator/src/lib.rs, xtask/Cargo.toml, xtask/src/gendocs.rs
With this patch, all sandboxing code is guarded by `#[cfg(unix)]`.
=> Build without sandboxing on Windows

CHANGELOG.md, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/commands/extensions/api.rs, cli/src/commands/project.rs, cli/src/format.rs, cli/src/types.rs, docs/commands/phylum_project_list.md, docs/commands/phylum_project_update.md, extensions/CHANGELOG.md
This patch updates the endpoints used for the project management
subcommands to avoid the soon-to-be deprecated overview endpoint.
The `phylum project update` subcommand has been updated to make use of
the new `default_label` field, which can now be updated.
The `phylum project list` subcommand now lists all projects by default,
including group projects. To still allow listing only non-group projects
the new `--no-group` flag has been added to this subcommand
specifically. The `repository_url` has been removed from the command
output, since it is not included in the API response.
The group name has been removed from `phylum project status`, since the
new endpoint used by the subcommand does not return this information.
However the `default_label` field was added instead.
Closes #1439.
=> Update project management endpoints

.github/workflows/release.yml
This patch adds a windows executable to the release artifacts. This build does not include extensions or sandboxing, so I have left it unsigned and will not be recommending it as a first choice for Windows.
=> Add windows binary to release

CHANGELOG.md, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/bin/phylum.rs, cli/src/commands/group.rs, cli/src/format.rs, cli/src/types.rs, doc_templates/phylum_group_create.md, doc_templates/phylum_group_delete.md, doc_templates/phylum_group_list.md, docs/commands/phylum_group_create.md, docs/commands/phylum_group_delete.md, docs/commands/phylum_group_list.md
This patch adds org support to the `list`/`create`/`delete` subcommands of `phylum group`. The `member` subcommand is unchanged, since user management is performed on the org level instead.
The `create` and `delete` subcommands will always use the currently linked organization, with no way to temporarily override it. While this could be annoying to some, it avoids adding extra flags that would get deprecated in the future. Most users likely always or never work within organizations and for people working in-between it's easiest to avoid linking orgs and just using `--org` instead as required.
See #1482.
=> Add org support to `phylum group`

CHANGELOG.md, cli/src/api/mod.rs, cli/src/bin/phylum.rs, cli/src/commands/extensions/api.rs, cli/src/commands/init.rs, cli/src/commands/jobs.rs, cli/src/commands/project.rs, cli/src/config.rs, cli/src/format.rs, cli/src/types.rs, cli/tests/common.rs, doc_templates/phylum_history.md, doc_templates/phylum_init.md, doc_templates/phylum_project_list.md, docs/commands/phylum_history.md, docs/commands/phylum_init.md, docs/commands/phylum_project_list.md, extensions/CHANGELOG.md, extensions/phylum.d.ts
This patch uses the `Config::org` function to add support for org
support in all subcommands that were still missing org support.
Generally when an org is linked, the org mode is always preferred. Only
in scenarios where no group is present at all, like `phylum project
delete <NAME>`, the personal projects will be used instead.
Since this could potentially lead to a lot of confusion with the project
management subcommands, all project subcommands have been changed to
print projects in a fixed format that lists the corresponding org and
group:
```
✅ Successfully deleted project cli (org: phylum, group: org-group)
```
```
✅ Successfully deleted project demo (org: -, group: -)
```
Closes https://github.com/phylum-dev/cli/issues/1482.
=> Add org support for init/project/analyze/history

.github/workflows/release.yml
Installing `cmake` is unnecessary and just causes [warnings][1] on our release workflow. The patch removes it from the workflow.
[1]: https://github.com/phylum-dev/cli/actions/runs/10798611911
=> Remove unneeded install in release workflow

CHANGELOG.md, extensions/bundle/README.md, extensions/cargo/README.md, extensions/npm/README.md, extensions/npm/main.ts, extensions/pip/README.md, extensions/poetry/README.md, extensions/yarn/README.md, extensions/yarn/main.ts
This change allows for local project directory write access
for the building stage of the `yarn` extension. This brings
it into parity with the rest of the package manager extensions.
The need for this change was discovered by a community edition
user who reported in Discord how the extension was failing due
to a sandbox access violation:
```
Error: EROFS: read-only file system, rmdir '/home/sum/DEV/ETH/YD/yd-marketplace/node_modules/.store'
```
The same user also noted their confusion over the language
provided by the extension after this failure:
> Please submit your lockfile to Phylum should this error persist.
They did not have a lockfile present (just a `package.json` manifest)
and noted that the extension did not create a `yarn.lock` lockfile
for them to submit.
Therefore, the …
=> Update `yarn` extension sandbox exception

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
- Organization management under the `phylum org` subcommand
- Organization support for existing subcommands
- `phylum project update --default-label` option to set a project's default label
- `phylum project list --no-group` flag to only show personal projects
- Full sandbox write access to project directory for building with `yarn` extension
- Lockfile parsing of bun-generated yarn lockfiles
- Maven lockfile generation on Windows
- `phylum batch` subcommand
=> Bump to v7.0.0

cli/src/api/mod.rs, cli/src/commands/extensions/api.rs, cli/src/commands/init.rs, cli/src/commands/project.rs, cli/src/format.rs, cli/src/types.rs
This switches all relevant endpoints from the combined "org/group" group name format to separate org and group name fields.
=> Switch to new org endpoint format

.github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md, bump_version.sh, cli/tests/extensions/permissions.rs, xtask/src/gendocs.rs
This change enables the extensions feature when building Windows release artifacts. Doing so will enable the `phylum-ci` tool to continue to operate with its extension-based analysis for the coming Windows standalone binary. Additional changes include:
* Consolidate `windows` job in `Test` workflow with `test-matrix` job
* Add Windows runner to `clippy` and `oldstable` `Test` workflow jobs
* Fix Windows clippy findings
* Remove extraneous `cmake` installs on macOS runners
* Fix `shellcheck` and `actionlint` findings
* Format throughout
=> Enable extensions for Windows release artifacts

.github/workflows/test.yml, .phylum_project, CHANGELOG.md, Cargo.lock, phylum_project/Cargo.toml, phylum_project/src/lib.rs
The changes made here are emulating those made in #1496, but for the `phylum_project` crate. This allows for more natural paths on Windows systems. Other changes made include:
* Update `.phylum_project` file for this repo
* Include the output/format from the current `phylum init` command
* Ensure `all-features` job in `Test` workflow has matching strategy
Output from a *nix system (macOS):
```
❯ phylum --version
phylum v7.0.0
❯ phylum status
Project: cli
Group: integrations
Project Root: /Users/maxrake/dev/phylum/localdev/cli
Dependency Files:
- path: /Users/maxrake/dev/phylum/localdev/cli/./Cargo.lock
type: cargo
❯ target/debug/phylum --version
phylum v7.0.0-3-g35f1873
❯ target/debug/phylum status
Project: cli
Group: integrations
Project Root: /Users/maxrake/dev/phylum/localdev/cli …
```
=> Fix Windows depfile paths in Phylum project files

.github/workflows/release.yml
All of our runners (including self-hosted runners) now have rustup available. So this patch removes the use of curl to install it.
=> Use pre-installed rustup

CHANGELOG.md, cli/src/api/mod.rs, cli/src/format.rs, cli/src/types.rs, extensions/bundle/main.ts, extensions/cargo/main.ts, extensions/npm/main.ts, extensions/phylum.d.ts, extensions/pip/main.ts, extensions/poetry/main.ts, extensions/yarn/main.ts
The `suppressed` field has been deprecated for months. This patch any usage in CLI.
=> Use suppression_reason instead of suppressed

CHANGELOG.md, cli/src/types.rs, extensions/CHANGELOG.md, extensions/phylum.d.ts
This fixes some compatibility issues between our current API and the CLI's own internal data structures.
Closes #1514.
Closes #1512.
=> Fix failure in package subcommand

CHANGELOG.md, cli/src/commands/packages.rs, cli/src/types.rs
This fixes an issue where packages would show up as passing Phylum's
analysis if they failed at any point of the pipeline.
Closes https://github.com/phylum-dev/cli/issues/351.
---
Depends on https://github.com/phylum-dev/cli/pull/1517.
=> Fix pipeline failures showing up as complete

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
Also moved an errant CHANGELOG entry.
Release-Version: v7.1.2
=> Bump to v7.1.2

CHANGELOG.md, Cargo.lock, cli/Cargo.toml
- `phylum package` showing complete packages as analysis failures
=> Bump to v7.1.3

CHANGELOG.md, lockfile/src/parsers/pypi.rs, tests/fixtures/requirements-locked.txt
A bug was discovered recently when attempting to parse a `pip` lockfile. That is, a `requirements*.txt` file containing exact versions (i.e., `==`) in all of it's requirement specifiers. Such a file should parse as a lockfile and not fall back to lockfile generation. However, if whitespace is included around the `==`, the parsing fails.
Whitespace is allowed in requirement specifiers. This change accounts for that. It also updates the test fixture to prevent regressions.
Ref: https://pip.pypa.io/en/stable/reference/requirement-specifiers/
=> Allow whitespace in `pip` requirement specifiers

cli/js/api.js, extensions/CHANGELOG.md
This change fixes an oversight from when org support was first added to the extension API. The new `organization` parameters were added to `extensions/phylum.d.ts` but not exposed for consumers in `cli/js/api.js`.
[See commit `f890fea`](https://github.com/phylum-dev/cli/commit/f890fea) or PR #1490
The changes from this PR were confirmed to work by using them in the `ci` extension for `phylum-ci` (after updating it to account for organizations).
A review of the default and community extensions revealed only one use of one of these changed API calls:
* `snyk-import`, for `createProject`
* https://github.com/phylum-dev/community-extensions/blob/4c878e27930a9cdd332d65b066e514b778ef9a9a/snyk-import/main.ts#L69
* https://github.com/phylum-dev/community-extensions/issues/46
=> Add `organization` parameters to `Phylum` object

cli/js/api.js, extensions/CHANGELOG.md
This change corrects an oversight in the extensions API where the `getJobStatusRaw` endpoint was returning the results as if the `getJobStatus` endpoint was called instead. The return types are indeed different.
=> Fix return type for `PhylumApi::getJobStatusRaw`

CHANGELOG.md, lockfile/src/javascript.rs, tests/fixtures/pnpm-lock-v5.yaml, tests/fixtures/pnpm-lock.yaml
This fixes an issue with the lockfile parser of PNPM v5 lockfiles which would incorrectly include metadata in the package version.
Closes #1538.
=> Fix PNPM v5 version parsing

CHANGELOG.md, lockfile/src/parsers/gem.rs, lockfile/src/ruby.rs, tests/fixtures/Gemfile.lock
This fixes an issue in the Ruby `Gemfile.lock` parser where version-specific dependencies like `ffi (1.17.0-x86_64-linux-gnu)` would cause the parser to crash.
Since new Ruby Gems are not allowed to contain dashes, this patch simply discards Gems that contain a `-` in their version. There are technically two versions of `asciidoctor-reducer` (`1.0.0-rc.1` and `1.0.0-beta.1`) which contain dashes, but those are neither commonly used, nor a security risk.
Closes #1540.
=> Ignore platform-specific gems

CHANGELOG.md, cli/tests/common.rs, docs/commands/phylum_analyze.md, docs/commands/phylum_init.md, docs/commands/phylum_parse.md, docs/supported_lockfiles.md, lockfile/src/csharp.rs, lockfile/src/lib.rs, tests/fixtures/packages.config
This adds support for `packages.config` files for the C# ecosystem under the new `NugetConfig` lockfile name.
The file format itself seems to be relatively simple, with just a list of package names and optional versions. The current test fixture is based on examples of this lockfile found on <https://github.com>.
Both `packages.config` on its own and `*.packages.config` are supported as valid names. Since this seems to be a lockfile there is no need for lockfile generation.
=> Add C# *.packages.config support

cli/src/auth/oidc.rs, cli/src/commands/extensions/api.rs, cli/src/commands/init.rs, cli/src/permissions.rs, cli/src/update/unix.rs, lockfile/src/cyclonedx.rs, lockfile/src/java.rs, lockfile/src/javascript.rs, lockfile/src/parsers/go_mod.rs, lockfile/src/python.rs, lockfile/src/spdx.rs
This fixes nightly clippy warnings, mainly the new suggestion to prefer `Option::is_some_and`/`Result::is_ok_and` over `.map_or(false, …)`. Despite these warnings not being stable yet, they are good suggestions to improve the code quality.
=> Fix nightly clippy warnings

CHANGELOG.md, lockfile/src/java.rs, lockfile/src/lib.rs
This change fixes a bug that is specific to Windows systems. When legacy Gradle (prior to v7.0.0) lockfiles exist (e.g.,
`gradle/dependency-locks/*.lockfile`) along with a manifest at a higher level, the manifest is meant to be ignored when finding dependency files to analyze. However, on Windows systems this was not the case before this change. Instead, both the manifest and the lockfiles were retained. After this change, only the lockfiles are retained when both are present.
A failing test was added first to confirm the incorrect behavior. Then, a change was made to handle paths as `Path` objects instead of strings. That way, the generic `/` path separator character will be used correctly regardless of the runtime system.
Additionally, an error message was updated to reflect the correct …
=> Fix Windows Gradle manifests incorrectly retained

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, extensions/CHANGELOG.md
=> Bump to v7.2.0

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/api/endpoints.rs, cli/src/api/mod.rs, cli/src/app.rs, cli/src/bin/phylum.rs, cli/src/commands/exception.rs, cli/src/commands/firewall.rs, cli/src/commands/mod.rs, cli/src/format.rs, cli/src/types.rs, docs/commands/phylum.md, docs/commands/phylum_exception.md, docs/commands/phylum_exception_add.md, docs/commands/phylum_exception_list.md, docs/commands/phylum_exception_remove.md, docs/commands/phylum_firewall_log.md
This patch adds a new `phylum exception` subcommand, with the three
`add`, `remove`, and `list` commands under it. These new subcommands
allow managing package exceptions to remove friction with Phylum's
firewall.
The add and remove subcommands are targeted at interactive use, pulling
logs from the package firewall and existing exceptions to suggest what
is most likely to be used for adding/removing an exception.
While currently firewall logs are pulled for adding exceptions, the
individual analysis results for each version are not listed in the
suggestions.
The `list` and `remove` subcommand allow managing both package and issue
suppressions, however `add` currently only supports adding package
exceptions.
Closes https://github.com/phylum-dev/cli/issues/1552.
---
This got a lot bigger …
=> Add phylum exception subcommand

CHANGELOG.md, lockfile/src/csharp.rs, tests/fixtures/sample.csproj
This change updates the `msbuild` lockfile parser so that it will not allow for missing names and or versions. Before this change, a `*.csproj` file parsed as a lockfile (e.g., with type of `msbuild`) would show entries with missing name or version as an empty string. This causes analysis failures when submitting to the API since a valid package descriptor requires a non-empty `version` field.
Dependency management in NuGet's "Central Package Management" (CPM) allows for `*.csproj` files containing `PackageReference` elements without a `Version` attribute. Those versions will be included, along with the fully transitive set, in the `packages.lock.json` lockfile generated by NuGet. When both files are present in the same directory, the changes in this patch will correctly parse both. For …
=> Fix `msbuild` parser allowing missing versions

cli/src/permissions.rs, cli/tests/extensions/permissions.rs, cli/tests/fixtures/extensions/permissions/correct-net-perms/PhylumExt.toml, cli/tests/fixtures/extensions/permissions/correct-net-perms/main.ts, cli/tests/fixtures/extensions/permissions/incorrect-net-perms/PhylumExt.toml, cli/tests/fixtures/extensions/permissions/incorrect-net-perms/main.ts, lockfile/src/cargo.rs, lockfile/src/python.rs, tests/fixtures/Cargo_v3.lock, tests/fixtures/requirements-locked.txt
This fixes an issue caused by phylum.io redirecting to veracode.com, which caused our sandbox to complain that network access permissions to veracode.com were missing.
Some other tests also used `phylum.io` as dummy URIs. While these were never hit, they've been replaced for consistency and future-proofing.
There are still several instances referencing `api.phylum.io` or `docs.phylum.io`, which have been left unchanged since no Veracode alternative exists yet.
=> Fix test failure to to phylum.io redirect

CHANGELOG.md, cli/src/permissions.rs
With Nix (including NixOS), software is installed into /nix/store and resolved using environment variables or configuration files or symbolic links. For example, if you install the jdk package your java installation will be somewhere like `/nix/store/3dhyjzr2j852wxgsaij64xgm74h6wgfp-openjdk-21.0.5+11/bin/java` and resolved using symbolic links or `PATH` depending on the installation method. Therefore, if `/nix/store` isn't readable and executable you won't be able to run anything installed using Nix (or practically anything at all on NixOS).
There is a chance that this allows a malicious package to read sensitive files under `/nix/store`. This should be uncommon. Users aren't supposed to put secrets directly into the Nix store because the files all have 0444 or 0555 permissions. However, …
=> add default exception for nix

CHANGELOG.md, cli/src/commands/parse.rs
MacOS normally installs JDKs in these locations: https://nanova.me/posts/macos-jdk-path
That page also references a `~/.jenv` directory which I did not add. I don't know if there's any reason not to add it.
=> add Mac Java paths to depfile_parsing_sandbox

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md, cli/Cargo.toml, cli/tests/extensions/mod.rs, cli/tests/sandbox.rs, doc_templates/phylum_group_member_add.md, doc_templates/phylum_group_member_remove.md, doc_templates/phylum_org_member_add.md, doc_templates/phylum_org_member_remove.md, docs/commands/phylum_group_member_add.md, docs/commands/phylum_group_member_remove.md, docs/commands/phylum_org_member_add.md, docs/commands/phylum_org_member_remove.md, docs/extensions/extension_manifest.md, docs/quickstart.md, extensions/bundle/README.md, extensions/cargo/README.md, extensions/npm/README.md, extensions/phylum.d.ts, extensions/pip/README.md, extensions/poetry/README.md, extensions/poetry/fixtures/pyproject.toml, extensions/yarn/README.md, lockfile/Cargo.toml, lockfile_generator/Cargo.toml, phylum_project/Cargo.toml, vulnreach_types/Cargo.toml
This change updates the `@phylum.io` emails to `@veracode.com` ones.
Related to phylum-dev/documentation#276
=> Update language for Veracode transition

.github/workflows/release.yml, .github/workflows/test.yml
This change updates the workflow runners to move away from the soon to
be deprecated `ubuntu-20.04` image and use `ubuntu-22.04` instead. The
intention is to continue to use the oldest supported version to ensure
binaries can build and run on that version. `ubuntu-latest` is used for
the linting related jobs.
Additionally, uses of `apt` were changed to `apt-get` to silence
warnings in CI about how `apt` is not meant to be used in scripts.
Ref: https://github.com/actions/runner-images/issues/11101
=> Update workflow runners

CHANGELOG.md, lockfile/src/cyclonedx.rs
Since CycloneDX v1.4, `version` is no longer a required field: https://cyclonedx.org/docs/1.4/json/#components_items_version
We also made the determination in Slack to just skip components that have a missing PURL. This patch has made an exception only for the missing PURL case, and no others. If we want to relax our input requirements further, we can discuss that here.
=> `version` and `purl` fields in `components` list are now optional in CycloneDX SBOMs.

.github/dependabot.yml, .github/workflows/cargo-update.yml, .github/workflows/release.yml, .github/workflows/test.yml
This change updates the `cargo-update` workflow to be more like the rest
of the repos in the `phylum-dev` org. That is, it will no longer fail if
an update PR already exists. Additional changes made include:
* Update macOS runners from `macos-14` to `macos-15`
* Use environment variable for the branch name to be DRY
* Allow major version tags when specifying trusted actions
* Update existing comments and add more comments
Resources:
* [Standard GitHub-hosted runners for public repos](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
* [Latest `macos-15` image release](https://github.com/actions/runner-images/releases/tag/macos-15-arm64%2F20250714.1971)
* [SW …
=> Update workflows to current standards
