- .github/workflows/release.yml
- README.md
Updates GH actions on release to:
* add configuration files and install script individually
* bundle all files into a release zip file
> Update actions to create release zip file and update README

- README.md
This PR just modifies README.md with an example submission with brief overview of how responses work, and how to query for verbose responses.
> Update README with example

- lib/src/bin/.conf/cli.yaml
- lib/src/bin/phylum-cli.rs
- lib/src/bin/phylum.bash
- lib/src/lib.rs
- lib/src/render.rs
Adding a `Renderable` trait to use for pretty-printing api responses.
> Adding rendering for command output

- lib/Cargo.lock
- lib/Cargo.toml
- lib/src/bin/.conf/cli.yaml
- lib/src/bin/phylum-cli.rs
- lib/src/bin/phylum.bash
- lib/src/types.rs
Add facilities for performing update checks, as well as a mechanism for performing updates in place (currently only supports Linux x64 as this is the only OS/Arch we are automating builds for).
> Add update mechanism

- lib/Cargo.lock
- lib/Cargo.toml
- lib/install.sh
- lib/src/api.rs
- lib/src/bin/.conf/cli.yaml
- lib/src/bin/phylum-cli.rs
- lib/src/bin/phylum.bash
- lib/src/lib.rs
- lib/src/render.rs
- lib/src/summarize.rs
- lib/src/types.rs
- lib/src/utils.rs
This PR adds formatted output for the `phylum analyze` subcommand (also used by the `phylum history` command when provided with a job id.
> Update `analyze` command

- lib/src/bin/phylum-cli.rs
> Print the update message to stderr instead of stdout

- lib/src/api.rs
- lib/src/bin/phylum-cli.rs
- lib/src/types.rs
> Query the remote endpoint when checking auth status

- lib/src/api.rs
- lib/src/bin/phylum-cli.rs
- lib/src/summarize.rs
If the number of incomplete packages is greater than zero, shows a
notice indicating the percentage of packages that still need to be
processed.
Also updates the web URL to point to the project.
> Add notice if packages are still processing.

- lib/install.sh
- lib/src/render.rs
- lib/src/summarize.rs
* Log-based scale for histogram
* Add install help message
* Normalize threshold values
closes #98, #99, #100
> Minor updates

- lib/install.sh
- lib/src/render.rs
- lib/src/summarize.rs
- lib/src/types.rs
Adds an additional status display for situations where the processing
has not completed yet.
Closes #102
> Add incomplete status display

- lib/src/filter.rs
- lib/src/summarize.rs
> Fix bug where vulns were not properly excluded by filters

- lib/install.sh
> Fix typo in install script file check

- lib/Cargo.lock
- lib/Cargo.toml
- lib/src/auth/ip_addr_ext.rs
- lib/src/test.rs
- lib/tests/logging/mod.rs
See if this fixes cross compile
> Swap out static_init module for lazy_static

- lib/src/api.rs
- lib/src/bin/phylum-cli/commands/projects.rs
- lib/src/bin/phylum-cli/prompt.rs
- lib/src/render.rs
- lib/src/summarize.rs
- lib/src/types/package.rs
* Remove unused `vulnerabilities` and `heuristics` fields
* Make `dependencies` a map to correspond with current staging environment
@peterjmorgan should fix the deserialization issue you were seeing with `--verbose`
> Updates for recent api changes

- cli/src/api/job.rs
- cli/src/auth/oidc.rs
- cli/src/lockfiles/mod.rs
- cli/src/lockfiles/parsers.rs
- cli/src/update.rs
- cli/tests/fixtures/complex-requirements.txt
- cli/tests/fixtures/requirements.txt
The PyPI parser was ignoring dots in package names.
Also update the parser to include git repositories.
@spellman I verified the other parsers handle a dot in the name.
What issue(s) does this PR close.
Closes #180
> Fix pypi parsing

- Cargo.lock
- cli/Cargo.toml
- cli/src/app.rs
- cli/src/bin/phylum/commands/jobs.rs
- cli/src/bin/phylum/commands/lock_files.rs
- cli/src/lockfiles/mod.rs
- cli/src/lockfiles/parsers.rs
- cli/src/render.rs
Provide information on what this PR does and any context necessary to understand its implementation.
What issue(s) does this PR close. Use the `closes #<issueNum>` here.
> Standardize package type names / add nuget package type

- cli/src/config.rs
Don't error when the config file doesn't exist. Instead, use reasonable defaults.
Fixes #192
> Allow binary to be run without config file

- README.md
Fix the badges so that they point to reasonable locations. Also updated the docs badge to be blue instead of barf colored.
closes #210
> Fix badges and links

- cli/src/bin/phylum.rs
Most instances of anyhow's context feature were using the error itself
as context while providing a nice readable message as error. However
this is the wrong way around.
To get the nice human readable message as error, one has to provide the
error itself as context.
This example shows the change with `PhylumApi`'s error handling:
Before:
```
[2022-04-07T17:19:18Z ERROR phylum] Execution failed: error decoding response body: missing field `access_token` at line 1 column 69
Caused by:
Error creating client
❗ Error: Execution failed caused by: error decoding response body: missing field `access_token` at line 1 column 69
```
After:
```
[2022-04-07T17:19:50Z ERROR phylum] Execution failed: Error creating client
Caused by:
0: error decoding response body: missing field `access_token` at line 1 …
```
> Fix anyhow context usage

- cli/src/auth/oidc.rs
The current error when trying to use the phylum CLI with an invalid
token is rather cryptic, making it hard to identify the root cause:
```
[2022-04-07T18:59:09Z ERROR phylum] Execution failed: Error creating client
Caused by:
0: error decoding response body: missing field `access_token` at line 1 column 69
1: missing field `access_token` at line 1 column 69
❗ Error: Execution failed caused by: Error creating client
```
To make things easier for the user to understand, the response from the
server is returned together with the status code for the request
failure, rather than just failing the attempted serde conversion:
```
[2022-04-07T18:03:05Z ERROR phylum] Execution failed: Error creating client
Caused by:
0: HTTP status client error (400 Bad Request) for url …
```
> Fix cryptic errors with invalid auth token

- docs/updating.md
> Documentation Update

- cli/src/lockfiles/javascript.rs
The parser was assuming that certain keys in the JSON would always exist
and this was leading to panic for some package-lock.json files. This
patch removes that assumption and fixes #338
> fix: Don't panic in the javascript lockfile parser

- cli/src/api/mod.rs
This enhances the verbosity of errors when an HTTP request failed, by
providing the full response with a response code other than 200, rather
than trying to parse the response as valid JSON.
This should shed more insights on why the request failed, especially
when the user has connectivity issues.
Closes #155.
> Improve error messages with HTTP failures

- cli/src/app.rs
- cli/src/commands/group.rs
- docs/phylum_analyze.md
- docs/phylum_group.md
- docs/phylum_group_create.md
- docs/phylum_group_list.md
- docs/phylum_project.md
- docs/phylum_project_create.md
- docs/phylum_project_link.md
- docs/phylum_project_list.md
- docs/phylum_project_set-thresholds.md
Updating user documentation to capture additional options and commands for group accounts
> docs: add docs for group accounts

- Cargo.lock
- cli/src/api/endpoints.rs
- cli/src/api/mod.rs
- cli/src/filter.rs
- cli/src/render.rs
- cli/src/summarize.rs
> Use new format for package analysis endpoint

- cli/src/summarize.rs
> Remove Web UI link from analyze output

- Cargo.lock
Update to latest phylum_types in order to fix phylum-dev/api#254
> Bump phylum_types version

- cli/src/bin/phylum.rs
This is a small refactor to the update check when the user is not
explicitly asking for an update.
It moves around some code to more accurately represent the intention of
what the code is suppose to do, while no functional changes are
introduced.
Closes #428.
> Refactor update check

- .github/workflows/cargo-update.yml
Using a PAT for @phylum-bot should allow the created PRs to kick off workflows.
Fix #432
> Use phylum-bot to create cargo update PRs

- cli/src/api/mod.rs
- cli/src/commands/group.rs
- cli/src/commands/mod.rs
- cli/src/commands/project.rs
> Add detailed messages for HTTP conflicts

- cli/src/config.rs
> Fix EOF error in config tests

- cli/src/bin/phylum.rs
- cli/src/commands/extensions/extension.rs
- cli/src/commands/extensions/mod.rs
- cli/src/deno.rs
- cli/tests/extensions/mod.rs
> `extensions run` subcommand

- README.md
- docs/command_line_tool/quickstart.md
- docs/support/contact_us.md
- Add Slack invitation link
- Add `Contact Us` page
> docs: Add Phylum Community Slack invitation

- CHANGELOG
- Cargo.lock
- cli/Cargo.toml
Release-Version: v3.7.2
Release-Summary: Improved error messages and output formatting
> Bump to v3.7.2 - Improved error messages and output formatting

- extensions/npm/PhylumExt.toml
- extensions/npm/main.ts
This adds pathrough of commands other than `npm install` to the `phylum
npm` extension.
> Update NPM extension with passthrough

- extensions/npm/main.ts
- extensions/poetry/main.ts
- extensions/yarn/PhylumExt.toml
- extensions/yarn/main.ts
This updates the yarn extension to bring it up to date with the latest
npm/poetry changes.
The npm/poetry changes have also gotten some minor adjustments to keep
everything in sync.
> Update yarn extension

- extensions/npm/README.md
- extensions/yarn/README.md
Mostly identical to `poetry`'s `README`.
> Added yarn and npm READMEs

- README.md
- docs/command_line_tool/alternate_install.md
- docs/command_line_tool/quickstart.md
Fix #619 by documenting our alternate install methods.
> Document alternate install methods

- cli/src/api/endpoints.rs
- cli/src/api/mod.rs
- cli/src/commands/project.rs
> Switch to new project thresholds endpoint

- .github/workflows/release.yml
Docs should not be updated until the official release.
> Don't update docs for pre-releases

- .github/workflows/release.yml
Delete a few characters to save the trees and close #614
> Re-enable compression

- cli/src/lockfiles/python.rs
- cli/tests/extensions/mod.rs
- cli/tests/fixtures/poetry.lock
Adds an additional source type to the parser. 
Closes https://github.com/phylum-dev/cli/issues/682
> Handle additional poetry source type

- Cargo.lock
Update birdcage dependency to incorporate the fix for phylum-dev/birdcage#11
> Bump birdcage

- Cargo.lock
- cli/Cargo.toml
- cli/src/commands/extensions/api.rs
- cli/src/commands/extensions/permissions.rs
- cli/src/deno.rs
> Update deno dependencies

- cli/src/api/mod.rs
- cli/src/commands/extensions/api.rs
- cli/src/extension_api.ts
- cli/tests/common.rs
- cli/tests/end_to_end/extension.rs
> Create project extensions API

- .github/workflows/test.yml
- cli/Cargo.toml
- lockfile/Cargo.toml
> Add CI compile-test for MSRV

- Cargo.lock
- cli/src/commands/extensions/api.rs
- cli/src/commands/extensions/permissions.rs
- cli/src/deno.rs
- cli/tests/extensions/mod.rs
- cli/tests/extensions/permissions.rs
- cli/tests/fixtures/extensions/permissions/correct-run-perms/PhylumExt.toml
- cli/tests/fixtures/extensions/permissions/correct-run-perms/main.ts
- docs/extensions/extension_sandboxing.md
- extensions/find-permissions/PhylumExt.toml
- extensions/npm/PhylumExt.toml
- extensions/npm/main.ts
- extensions/poetry/PhylumExt.toml
- extensions/yarn/PhylumExt.toml
> Layered sandbox permissions

- cli/src/commands/extensions/api.rs
- cli/src/commands/extensions/extension.rs
- cli/src/commands/extensions/state.rs
- cli/src/deno.rs
- cli/src/extension_api.ts
- cli/tests/extensions/permissions.rs
> Permissions extensions API

- cli/src/commands/extensions/mod.rs
- docs/extensions/extension_manifest.md
Update the docs and install code to clarify the connection between read and run permissions.
Fixes #785
> Clarify connection between read and run permissions

- .github/workflows/cargo-update.yml
- .github/workflows/release.yml
This patch fixes some issues that were introduced in #816
Thanks @maxrake for keeping a sharp eye on our PRs.
> Fix regressions in #816

- extensions/npm/main.ts
- extensions/poetry/main.ts
- extensions/yarn/main.ts
This patch resolves an issue with the ecosystem extensions where the dry run could potentially leave the project manifest and lockfile modified if the extension failed a `PhylumApi` call, since this introduces an exception.
To ensure backups are always restored after the dry run, we catch the exception, restore and then throw it again. Throwing the same exception has the advantage that error formatting is persisted.
This also fixes an issue in all three ecosystem extensions where calls to the async `abort` function were not awaited. As a result it was possible that execution continued despite explicitly trying to abort.
Closes #860.
> Restore files on ecosystem extension API failure

- Cargo.lock
- lockfile/src/lib.rs
> Remove unused type alias

- CHANGELOG
- Cargo.lock
- cli/Cargo.toml
Release-Version: v4.2.0
Release-Summary: Single package submit
> Bump to v4.2.0 - Single package submit

- cli/src/config.rs
This patch changes the way configuration files are written to first write their contents to a temporary file before then moving that file into place atomically. As a result the configuration file is always present and never contains partial data.
While I wasn't able to reproduce the issue locally, it should fix any test failures due to the configuration file not being accessible temporarily after writing to it.
Closes #851.
> Make config file write atomic

- README.md
See: https://github.com/badges/shields/issues/8671
> chore: fix README test status badge

- cli/src/commands/extensions/permissions.rs
Previously we were resolving relative paths through `$PATH` by adding their path to each entry in `$PATH` and checking if the resulting path exists. This could easily lead to wrong results for paths like `.` which would always exist when adding it to any path in `$PATH`.
To ensure path resolution only works when the full path specified is actually an executable in any directory in `$PATH`, we walk the `$PATH` directories instead and check if its entries' file names matches the requested path exactly.
> Fix sandbox executable path resolution

- CHANGELOG
- Cargo.lock
- cli/Cargo.toml
Release-Version: v4.6.0
Release-Summary: Improve init UX
> Bump to v4.6.0 - Improve `init` UX

- README.md
- docs/command_line_tool/quickstart.md
- docs/support/contact_us.md
Updating docs to point to discord instead of slack
> docs: Update from Slack to Discord

- cli/src/commands/init.rs
> Fix inconsistent `phylum init` whitespace

- cli/Cargo.toml
- cli/tests/common.rs
- cli/tests/config.rs
- cli/tests/extensions/mod.rs
- cli/tests/extensions/module_loader.rs
- cli/tests/extensions/permissions.rs
- cli/tests/parse.rs
- cli/tests/sandbox.rs
- xtask/src/gendocs.rs
This was run with rustc 1.68.0
> cargo clippy --fix

- CHANGELOG
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
Release-Version: v5.0.0
Release-Summary: Policy operation
> Bump to v5.0.0 - Policy operation

- .github/workflows/release.yml
> Populate release notes from changelog

- cli/tests/end_to_end/extension.rs
Get back to green by cheating!
> Temporarily disable get_package_details test

- CHANGELOG.md
- extensions/CHANGELOG.md
Clarify changelogs and remove empty version
> Specify which changes should be noted in each changelog

- CHANGELOG.md
This adds the missing changelog entry for bdab0df.
> Add `phylum status` CHANGELOG entry

- CHANGELOG.md
This change was made in #1060 and it's notable enough to deserve a changelog entry
> Mention `npm-shrinkwrap.json` support in CHANGELOG

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
Release-Version: v5.1.0
Release-Summary: Manifest file support
> Bump to v5.1.0 - Manifest file support

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.2.0

- lockfile/src/python.rs
- lockfile_generator/src/lib.rs
- lockfile_generator/src/pip_tools.rs
- lockfile_generator/src/pipenv.rs
> Rename pip and python_requirements generators

- README.md
- docs/command_line_tool/quickstart.md
> Mention Homebrew caveat in install instructions

- CHANGELOG.md
These CHANGELOG entries are for changes made in b78793e and ee167b3
> Add missed CHANGELOG entries

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.4.0

- .cargo/config
- .github/workflows/release.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- Cargo.lock
- cli/tests/integration.rs
- lockfile/src/lib.rs
- xtask/Cargo.toml
- xtask/src/gencomp.rs
- xtask/src/gendocs.rs
- xtask/src/main.rs
Faster tests with less disk space required
> Run tests in parallel

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.6.0

- CHANGELOG.md
- cli/src/commands/parse.rs
> Use relative path for manifest files

- extensions/bundle/README.md
- extensions/npm/README.md
- extensions/pip/README.md
- extensions/poetry/README.md
- extensions/yarn/README.md
> Update READMEs for ecosystem extensions

- cli/src/commands/extensions/extension.rs
This patch updates the install check to correctly handle relative paths. Before this, it was possible to fool the check by using a relative path on the command line.
```
> phylum extension install -y ~/.local/share/phylum/extensions/npm
Installing extension npm...
❗ Error: extension path and installation path are identical, skipping
> phylum extension install -y ./.local/share/phylum/extensions/npm
Installing extension npm...
❗ Error: IO error for operation on ./.local/share/phylum/extensions/npm: No such file or directory (os error 2)
```
I believe the previous check could also be fooled with an absolute path on the command line if `XDG_DATA_HOME` contained a relative path. But that scenario is very unlikely, so I did not test it.
> Use absolute paths for install check

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
- extensions/npm/main.ts
- lockfile/src/cyclonedx.rs
> Bump to v5.7.0

- docs/knowledge_base/analyzing-dependencies.md
Updates documentation to reflect the supported file formats for CycloneDX SBOMs.
> Update CycloneDX documentation

- CHANGELOG.md
- lockfile/src/javascript.rs
- tests/fixtures/package-lock.json
Fix #1227 by ignoring extraneous packages
> Ignore extraneous npm dependencies

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.7.1

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.7.2

- CHANGELOG.md
- lockfile/src/javascript.rs
- tests/fixtures/pnpm-lock.yaml
> Fix path dependencies for pnpm lockfile parser

- lockfile/src/lib.rs
This patch changes the logic of `LockableFiles::at` to build independent lockfile and manifest lists, allowing one file to be present in both.
This does not have any impact on `find_lockable_files_at`, so a file that is both a manifest and a lockfile will still only appear once.
> Classify lockfiles and manifests independently

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.8.0

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.8.1

- CHANGELOG.md
- cli/src/commands/project.rs
> Show project ID after creation

- cli/src/commands/parse.rs
> Fix cargo lockfile generation sandbox exceptions

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v5.9.0

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.0.0

- cli/src/commands/parse.rs
Previously the STDERR of the sandboxed `parse-sandboxed` subcommand was only forwarded if the command failed. Now the STDERR is always inherited regardless of exit status.
To ensure optimal troubleshooting in case of a failure, the STDOUT is now also printed to STDOUT in case of a failure.
Closes #1329.
> Forward parse-sandboxed STDERR on success

- cli/src/filter.rs
- cli/src/format.rs
- cli/src/types.rs
https://github.com/phylum-dev/api/pull/1176 introduced some breaking changes in the API that now have to be accomodated in downstream code such as the UI and CLI.
> Accomodate API breaking changes around issues.

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.1.0

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
> Bump to v6.1.1

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.5.0

- CHANGELOG.md
- lockfile/src/javascript.rs
- lockfile/src/lib.rs
- tests/fixtures/pnpm-lock-v5.yaml
> Add PNPM lockfile version 5 support

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.6.0

- cli/src/api/mod.rs
- cli/src/commands/parse.rs
- lockfile/src/javascript.rs
This patch resolves some issues with Maven's lockfile generation on Debian-based systems.
> Add missing mvn exceptions

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.6.1

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.6.2

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.6.3

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.6.5

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v6.6.6

- cli/Cargo.toml
- cli/src/app.rs
- cli/src/bin/phylum.rs
- cli/src/commands/extensions/api.rs
- cli/src/commands/extensions/extension.rs
- cli/src/commands/extensions/mod.rs
- cli/src/commands/mod.rs
- cli/src/commands/parse.rs
- cli/src/commands/sandbox.rs
- cli/src/lib.rs
- cli/src/permissions.rs
- cli/tests/common.rs
- cli/tests/end_to_end/extension.rs
- cli/tests/extensions/mod.rs
- cli/tests/extensions/permissions.rs
- cli/tests/integration.rs
This should simplify building the CLI on other targets (such as Windows)
> Make extensions optional with feature flag

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v7.1.0

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v7.1.1

- CHANGELOG.md
- cli/src/commands/packages.rs
> Fix unprocessed packages showing as complete

- CHANGELOG.md
- cli/src/commands/packages.rs
> Treat empty string in pipeline_error as success

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v7.1.4

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v7.1.5

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- extensions/CHANGELOG.md
> Bump to v7.3.0

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
> Bump to v7.5.0
